
###### SENSOR TEMPLATES ------------------------------------------
sensor:
  - platform: template
    sensors:
      appletv_kitchen_current_media:
        friendly_name: AppleTV Kitchen Current Media
        value_template: "{{ state_attr('media_player.appletv_kitchen', 'media_content_type') }}"

      appletv_kitchen_current_app:
        friendly_name: AppleTV Kitchen Current App
        value_template: "{{ state_attr('media_player.appletv_kitchen', 'app_name') }}"

      appletv_kitchen_current_title:
        friendly_name: AppleTV Kitchen Current Title
        value_template: "{{ state_attr('media_player.appletv_kitchen', 'media_title') }}"

      appletv_kitchen_current_artist:
        friendly_name: AppleTV Kitchen Current Artist
        value_template: "{{ state_attr('media_player.appletv_kitchen', 'media_artist') }}"

      appletv_kitchen_current_album:
        friendly_name: AppleTV Kitchen Current Album
        value_template: "{{ state_attr('media_player.appletv_kitchen', 'media_album_name') }}"
