### Configuration
homeassistant:
  name: !secret location
  latitude: !secret latitude
  longitude: !secret longitude
  # In Meters
  elevation: !secret elevation
  # metric, imperial
  unit_system: imperial
  # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone
  customize: !include customize.yaml
  packages: !include_dir_named packages
  auth_providers:
    - type: homeassistant
#    - type: trusted_networks
#      trusted_networks:
#        - 192.168.3.0/24
default_config:
cloud:
mobile_app:
discovery:
http:
sensor: !include_dir_merge_list sensors/
group: !include groups.yaml
automation: !include_dir_merge_list automation/
script: !include_dir_merge_named scripts/
scene: !include_dir_merge_list scenes/
input_boolean: !include_dir_merge_named input_booleans/

# UI
frontend:
  themes: !include_dir_merge_named themes/
lovelace:
  mode: yaml
  resources:
    - url: /local/custom-card/button-card.js
      type: module
    - url: /local/custom-card/card-mod.js
      type: module
    - url: /local/custom-card/mini-graph-card-bundle.js?v=0.9.4
      type: module
    - url: /local/custom-card/mini-media-player-bundle.js?v=1.9.1
      type: module
    - url: /local/custom-card/slider-entity-row.js
      type: module

# Wyze Sense
binary_sensor:
  - platform: wyzesense
    device: auto

# Garage Door
#cover:
#  - platform: myq
#    username: !secret myq_username
#    password: !secret myq_password
#    type: !secret myq_type

# Cameras
camera:
  - platform: ffmpeg
    name: FrontDoor
    input: !secret camera_RTSP_FrontDoor
  - platform: ffmpeg
    name: Garage
    input: !secret camera_RTSP_Garage
#  - platform: ffmpeg
#    name: Pancake
#    input: !secret camera_RTSP_Pancake
ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg

# iOS
ios:
  push:
    categories: !include_dir_merge_list ios/

#Switches
lutron_caseta_pro:
    bridges:
      - host: !secret caseta_bridge_ip
        mac: !secret caseta_bridge_mac
        switch: [ 9 ]
        fan: [ 11, 16, 25 ]
switch:
  - platform: broadlink
#    host: !secret broadlink_living_ip
    mac: !secret broadlink_living_mac
  - platform: broadlink
#    host: !secret broadlink_master_ip
    mac: !secret broadlink_master_mac

# Text to speech
tts:
  - platform: google_translate

#vesync:
#  username: !secret vesync_username
#  password: !secret vesync_password

zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_network_key
