title: Utopia
button_card_templates:
  !include /config/lovelace/button_card_templates.yaml
views:
  - !include /config/lovelace/views/security/security.yaml
  - !include /config/lovelace/views/house/house.yaml
  - !include /config/lovelace/views/living_room/living_room.yaml
  - !include /config/lovelace/views/bedroom/bedroom.yaml
  - !include /config/lovelace/views/office/office.yaml
  - !include /config/lovelace/views/theater/theater.yaml
  - !include /config/lovelace/views/rack/rack.yaml
