title: Utopia
resources:
  - url: /local/custom-card/button-card.js
    type: module
  - url: /local/custom-card/card-mod.js
    type: module
  - url: /local/custom-card/mini-media-player-bundle.js?v=1.9.1
    type: module
  - url: /local/custom-card/slider-entity-row.js
    type: module
  - url: /local/light-popup-card.js
    type: module
button_card_templates:
  !include /config/lovelace/button_card_templates.yaml
views:
  - !include /config/lovelace/views/security/security.yaml
  - !include /config/lovelace/views/house/house.yaml
  - !include /config/lovelace/views/living_room/living_room.yaml
  - !include /config/lovelace/views/bedroom/bedroom.yaml
  - !include /config/lovelace/views/office/office.yaml
  - !include /config/lovelace/views/theater/theater.yaml
  - !include /config/lovelace/views/rack/rack.yaml
popup_cards:
  light_stairs:
    title: ""
    style:
      $: |
        .mdc-dialog .mdc-dialog__container {
          width: 100%;
        }
        .mdc-dialog .mdc-dialog__container .mdc-dialog__surface {
          width:100%;
          box-shadow:none;
        }
      .: |
        :host {
          --mdc-theme-surface: rgba(0,0,0,0);
          --secondary-background-color: rgba(0,0,0,0);
          --ha-card-background: rgba(0,0,0,0);
          --mdc-dialog-scrim-color: rgba(0,0,0,0.8);
          --mdc-dialog-min-height: 100%;
          --mdc-dialog-min-width: 100%;
          --mdc-dialog-max-width: 100%;
        }
        mwc-icon-button {
          color: #FFF;
        }
    card:
      type: custom:light-popup-card
      entity: light.living_room_stairs
      icon: mdi:globe-light
      actionsInARow: 2
      brightnessWidth: 150px
      brightnessHeight: 400px
      switchWidth: 150px
      switchHeight: 400px
      actions:
        - action: call-service
          service: scene.turn_on
          service_data:
            entity_id: scene.ontspannen
          color: "#FDCA64"
          name: Scene 1
        - action: call-service
          service: scene.turn_on
          service_data:
            entity_id: scene.helder
          color: "#FFE7C0"
          name: Scene 2
