title: Utopia
resources:
  - url: /local/custom-card/button-card.js
    type: module
  - url: /local/custom-card/card-mod.js
    type: module
  - url: /local/custom-card/mini-media-player-bundle.js?v=1.9.1
    type: module
  - url: /local/custom-card/slider-entity-row.js
    type: module
#  - url: /local/custom-card/light-popup-card.js
#    type: module
#  - url: /browser_mod.js
#    type: module
button_card_templates:
  !include /config/lovelace/button_card_templates.yaml
views:
  - !include /config/lovelace/views/security/security.yaml
  - !include /config/lovelace/views/house/house.yaml
  - !include /config/lovelace/views/living_room/living_room.yaml
  - !include /config/lovelace/views/bedroom/bedroom.yaml
  - !include /config/lovelace/views/office/office.yaml
  - !include /config/lovelace/views/theater/theater.yaml
  - !include /config/lovelace/views/rack/rack.yaml
