
###### TEMPLATES ------------------------------------------

sensor:
  - platform: template
    sensors:
      master_bedroom_fan_percentage:
        friendly_name: Master Bedroom Fan Percentage
        value_template: "{{ state_attr('fan.master_bedroom_ceiling_fan', 'percentage') }}"
      master_bedroom_fan_speed:
        friendly_name: Master Bedroom Fan Speed
        value_template: >-
          {% if is_state('sensor.master_bedroom_fan_percentage', '0') %}
            off
          {% elif is_state('sensor.master_bedroom_fan_percentage', '25') %}
            low
          {% elif is_state('sensor.master_bedroom_fan_percentage', '50') %}
            medium
          {% elif is_state('sensor.master_bedroom_fan_percentage', '75') %}
            medium_high
          {% elif is_state('sensor.master_bedroom_fan_percentage', '100') %}
            high
          {% else %}
            unknown
          {% endif %}

###### SCRIPTS ------------------------------------------
script:

  fan_master_off:
    sequence:
      - service: fan.turn_off
        target:
          entity_id: fan.master_bedroom_ceiling_fan
  fan_master_low:
    sequence:
      - service: fan.set_percentage
        target:
          entity_id: fan.master_bedroom_ceiling_fan
        data:
          percentage: 25
  fan_master_medium:
    sequence:
      - service: fan.set_percentage
        target:
          entity_id: fan.master_bedroom_ceiling_fan
        data:
          percentage: 50
  fan_master_medium_high:
    sequence:
      - service: fan.set_percentage
        target:
          entity_id: fan.master_bedroom_ceiling_fan
        data:
          percentage: 75
  fan_master_high:
    sequence:
      - service: fan.set_percentage
        target:
          entity_id: fan.master_bedroom_ceiling_fan
        data:
          percentage: 100

  fan_toggle_master_low:
    sequence:
      - service: script.turn_on
        data_template:
          entity_id: >
            {% if is_state("sensor.master_bedroom_fan_speed", "low") %}
              script.fan_master_off
            {% else %}
              script.fan_master_low
            {% endif %}
  fan_toggle_master_medium:
    sequence:
      - service: script.turn_on
        data_template:
          entity_id: >
            {% if is_state("sensor.master_bedroom_fan_speed", "medium") %}
              script.fan_master_off
            {% else %}
              script.fan_master_medium
            {% endif %}
  fan_toggle_master_medium_high:
    sequence:
      - service: script.turn_on
        data_template:
          entity_id: >
            {% if is_state("sensor.master_bedroom_fan_speed", "medium_high") %}
              script.fan_master_off
            {% else %}
              script.fan_master_medium_high
            {% endif %}
  fan_toggle_master_high:
    sequence:
      - service: script.turn_on
        data_template:
          entity_id: >
            {% if is_state("sensor.master_bedroom_fan_speed", "high") %}
              script.fan_master_off
            {% else %}
              script.fan_master_high
            {% endif %}
