
###### TEMPLATES ------------------------------------------

sensor:
  - platform: template
    sensors:
      master_fan_percentage:
        friendly_name: Master Fan Percentage
        value_template: "{{ state_attr('fan.master_ceiling_fan', 'percentage') }}"


###### SCRIPTS ------------------------------------------
script:

  fan_master_off:
    sequence:
      - service: fan.turn_off
        target:
          entity_id: fan.master_ceiling_fan
  fan_master_low:
    sequence:
      - service: fan.set_percentage
        target:
          entity_id: fan.master_ceiling_fan
        data:
          percentage: 25
  fan_master_medium:
    sequence:
      - service: fan.set_percentage
        target:
          entity_id: fan.master_ceiling_fan
        data:
          percentage: 50
  fan_master_medium_high:
    sequence:
      - service: fan.set_percentage
        target:
          entity_id: fan.master_ceiling_fan
        data:
          percentage: 75
  fan_master_high:
    sequence:
      - service: fan.set_percentage
        target:
          entity_id: fan.master_ceiling_fan
        data:
          percentage: 100

  fan_toggle_master_low:
    sequence:
      - service: script.turn_on
        data_template:
          entity_id: >
            {% if is_state("sensor.master_fan_percentage", "25") %}
              script.fan_master_off
            {% else %}
              script.fan_master_low
            {% endif %}
  fan_toggle_master_medium:
    sequence:
      - service: script.turn_on
        data_template:
          entity_id: >
            {% if is_state("sensor.master_fan_percentage", "50") %}
              script.fan_master_off
            {% else %}
              script.fan_master_medium
            {% endif %}
  fan_toggle_master_medium_high:
    sequence:
      - service: script.turn_on
        data_template:
          entity_id: >
            {% if is_state("sensor.master_fan_percentage", "75") %}
              script.fan_master_off
            {% else %}
              script.fan_master_medium_high
            {% endif %}
  fan_toggle_master_high:
    sequence:
      - service: script.turn_on
        data_template:
          entity_id: >
            {% if is_state("sensor.master_fan_percentage", "100") %}
              script.fan_master_off
            {% else %}
              script.fan_master_high
            {% endif %}
