
###### TEMPLATES ------------------------------------------

sensor:
  - platform: template
    sensors:
      theater_fan_percentage:
        friendly_name: Theater Fan Percentage
        value_template: "{{ state_attr('fan.theater_ceiling_fan', 'percentage') }}"


###### SCRIPTS ------------------------------------------
script:

  fan_theater_off:
    sequence:
      - service: fan.turn_off
        target:
          entity_id: fan.theater_ceiling_fan
  fan_theater_low:
    sequence:
      - service: fan.set_percentage
        target:
          entity_id: fan.theater_ceiling_fan
        data:
          percentage: 25
  fan_theater_medium:
    sequence:
      - service: fan.set_percentage
        target:
          entity_id: fan.theater_ceiling_fan
        data:
          percentage: 50
  fan_theater_medium_high:
    sequence:
      - service: fan.set_percentage
        target:
          entity_id: fan.theater_ceiling_fan
        data:
          percentage: 75
  fan_theater_high:
    sequence:
      - service: fan.set_percentage
        target:
          entity_id: fan.theater_ceiling_fan
        data:
          percentage: 100

  fan_toggle_theater_low:
    sequence:
      - service: script.turn_on
        data_template:
          entity_id: >
            {% if is_state("sensor.theater_fan_percentage", "25") %}
              script.fan_theater_off
            {% else %}
              script.fan_theater_low
            {% endif %}
  fan_toggle_theater_medium:
    sequence:
      - service: script.turn_on
        data_template:
          entity_id: >
            {% if is_state("sensor.theater_fan_percentage", "50") %}
              script.fan_theater_off
            {% else %}
              script.fan_theater_medium
            {% endif %}
  fan_toggle_theater_medium_high:
    sequence:
      - service: script.turn_on
        data_template:
          entity_id: >
            {% if is_state("sensor.theater_fan_percentage", "75") %}
              script.fan_theater_off
            {% else %}
              script.fan_theater_medium_high
            {% endif %}
  fan_toggle_theater_high:
    sequence:
      - service: script.turn_on
        data_template:
          entity_id: >
            {% if is_state("sensor.theater_fan_percentage", "100") %}
              script.fan_theater_off
            {% else %}
              script.fan_theater_high
            {% endif %}
