
###### TEMPLATES ------------------------------------------

sensor:
  - platform: template
    sensors:
      theater_fan_percentage:
        friendly_name: Theater Fan Percentage
        value_template: "{{ state_attr('fan.theater_ceiling_fan', 'percentage') }}"
      theater_fan_speed:
        friendly_name: Theater Fan Speed
        value_template: >-
          {% if is_state('sensor.theater_fan_percentage', '0') %}
            off
          {% elif is_state('sensor.theater_fan_percentage', '25') %}
            low
          {% elif is_state('sensor.theater_fan_percentage', '50') %}
            medium
          {% elif is_state('sensor.theater_fan_percentage', '75') %}
            medium_high
          {% elif is_state('sensor.theater_fan_percentage', '100') %}
            high
          {% else %}
            unknown
          {% endif %}

###### SCRIPTS ------------------------------------------
script:

  fan_theater_off:
    sequence:
    - service: fan.turn_off
      target:
        entity_id: fan.theater_ceiling_fan
  fan_theater_low:
    sequence:
    - service: fan.set_percentage
      target:
        entity_id: fan.theater_ceiling_fan
      data:
        percentage: 25
  fan_theater_medium:
    sequence:
    - service: fan.set_percentage
      target:
        entity_id: fan.theater_ceiling_fan
      data:
        percentage: 50
  fan_theater_medium_high:
    sequence:
    - service: fan.set_percentage
      target:
        entity_id: fan.theater_ceiling_fan
      data:
        percentage: 75
  fan_theater_high:
    sequence:
    - service: fan.set_percentage
      target:
        entity_id: fan.theater_ceiling_fan
      data:
        percentage: 100

  fan_toggle_theater_low:
    sequence:
    - service: script.turn_on
      data_template:
        entity_id: >
          {% if is_state("sensor.theater_fan_speed", "low") %}
            script.fan_theater_off
          {% else %}
            script.fan_theater_low
          {% endif %}
  fan_toggle_theater_medium:
    sequence:
    - service: script.turn_on
      data_template:
        entity_id: >
          {% if is_state("sensor.theater_fan_speed", "medium") %}
            script.fan_theater_off
          {% else %}
            script.fan_theater_medium
          {% endif %}
  fan_toggle_theater_medium_high:
    sequence:
    - service: script.turn_on
      data_template:
        entity_id: >
          {% if is_state("sensor.theater_fan_speed", "medium_high") %}
            script.fan_theater_off
          {% else %}
            script.fan_theater_medium_high
          {% endif %}
  fan_toggle_theater_high:
    sequence:
    - service: script.turn_on
      data_template:
        entity_id: >
          {% if is_state("sensor.theater_fan_speed", "high") %}
            script.fan_theater_off
          {% else %}
            script.fan_theater_high
          {% endif %}
