
#cover:
#  - platform: template
#    covers:
#      shades_master:
#        device_class: shade
#        friendly_name: "Master Screen"
#        value_template: "{{ states('input_select.master_shade_screen') }}"
#        open_cover:
#          service: script.master_shade_screen_open
#        close_cover:
#          service: script.master_shade_screen_close
#        stop_cover:
#          service: script.master_shade_screen_stop

###### SENSOR TEMPLATES ------------------------------------------
#sensor:

###### INPUT BOOLEANS ------------------------------------------
#input_boolean:

###### INPUT SELECT ------------------------------------------
input_select:
  master_shade_screen:
    name: 'Master Screen'
    options:
      - open
      - opening
      - favorite
      - closing
      - closed


###### AUTOMATIONS --------------------------------------
automation:
- alias: Master Screen Open
  trigger:
  - platform: state
    entity_id: input_select.master_shade_screen
    to: "opening"
    for: "00:00:10"
  condition:
  - condition: template
    value_template: "{{ trigger.from_state.state != 'closed' }}"
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.master_shade_screen
      option: open
- alias: Master Screen Closed
  trigger:
  - platform: state
    entity_id: input_select.master_shade_screen
    to: "closing"
    for: "00:00:10"
  condition:
  - condition: template
    value_template: "{{ trigger.from_state.state != 'open' }}"
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.master_shade_screen
      option: closed
- alias: Master Screen Open Full Motion
  trigger:
  - platform: state
    entity_id: input_select.master_shade_screen
    to: "opening"
    for: "00:00:19"
  condition: []
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.master_shade_screen
      option: open
- alias: Master Screen Closed Full Motion
  trigger:
  - platform: state
    entity_id: input_select.master_shade_screen
    to: "closing"
    for: "00:00:19"
  condition: []
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.master_shade_screen
      option: closed

- alias: Master Screen Open Tracking
  trigger:
  - platform: state
    entity_id: cover.master_screen
    to: "open"
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.master_shade_screen
      option: open
- alias: Master Screen Closed Tracking
  trigger:
  - platform: state
    entity_id: cover.master_screen
    to: "closed"
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.master_shade_screen
      option: closed

###### SCRIPTS ------------------------------------------
script:
  master_shade_screen_open:
    sequence:
      - service: cover.open_cover
        data:
          entity_id: cover.master_screen
      - service: input_select.select_option
        data:
          entity_id: input_select.master_shade_screen
          option: opening
  master_shade_screen_stop:
    sequence:
      - service: cover.stop_cover
        data:
          entity_id: cover.master_screen
      - service: input_select.select_option
        data:
          entity_id: input_select.master_shade_screen
          option: favorite
  master_shade_screen_close:
    sequence:
      - service: cover.close_cover
        data:
          entity_id: cover.master_screen
      - service: input_select.select_option
        data:
          entity_id: input_select.master_shade_screen
          option: closing
