
cover:
  - platform: template
    covers:
      theater_screen:
#        device_class:
        friendly_name: "Projector Screen"
        value_template: "{{ states('input_select.theater_screen') }}"
        open_cover:
          service: script.theater_screen_open
        close_cover:
          service: script.theater_screen_close

###### SENSOR TEMPLATES ------------------------------------------
#sensor:

###### INPUT BOOLEANS ------------------------------------------
#input_boolean:

###### INPUT SELECT ------------------------------------------
input_select:
  theater_screen:
    name: 'Theater Screen'
    options:
      - open
      - opening
      - closing
      - closed

###### AUTOMATIONS --------------------------------------
automation:
- alias: Theater Screen Open
  trigger:
  - platform: state
    entity_id: input_select.theater_screen
    to: "opening"
    for: "00:00:07"
  condition:
  - condition: template
    value_template: "{{ trigger.from_state.state != 'closed' }}"
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.theater_screen
      option: open
- alias: Theater Screen Closed
  trigger:
  - platform: state
    entity_id: input_select.theater_screen
    to: "closing"
    for: "00:00:07"
  condition:
  - condition: template
    value_template: "{{ trigger.from_state.state != 'open' }}"
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.theater_screen
      option: closed
- alias: Theater Screen Open Full Motion
  trigger:
  - platform: state
    entity_id: input_select.theater_screen
    to: "opening"
    for: "00:00:14"
  condition: []
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.theater_screen
      option: open
- alias: Theater Screen Closed Full Motion
  trigger:
  - platform: state
    entity_id: input_select.theater_screen
    to: "closing"
    for: "00:00:14"
  condition: []
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.theater_screen
      option: closed

- alias: Theater Screen Open Tracking
  trigger:
  - platform: state
    entity_id: cover.theater_screen
    to: "open"
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.theater_screen
      option: open
- alias: Theater Screen Closed Tracking
  trigger:
  - platform: state
    entity_id: cover.theater_screen
    to: "closed"
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.theater_screen
      option: closed

###### SCRIPTS ------------------------------------------
script:
  theater_screen_close:
    sequence:
      - service: switch.turn_on
        data:
          entity_id: switch.relay_theater_screen_up
      - service: input_select.select_option
        data:
          entity_id: input_select.theater_screen
          option: closing
      - service: switch.turn_off
        data:
          entity_id: switch.relay_theater_screen_up
  theater_screen_open:
    sequence:
      - service: cover.close_cover
        data:
          entity_id: cover.theater_roman
      - service: switch.turn_on
        data:
          entity_id: switch.relay_theater_screen_down
      - service: input_select.select_option
        data:
          entity_id: input_select.theater_screen
          option: opening
      - service: switch.turn_off
        data:
          entity_id: switch.relay_theater_screen_down
