
cover:
  - platform: template
    covers:
      theater_screen:
#        device_class:
        friendly_name: "Projector Screen"
        value_template: "{{ states('input_select.theater_screen') }}"
        open_cover:
          service: script.theater_screen_open
        close_cover:
          service: script.theater_screen_close

###### SENSOR TEMPLATES ------------------------------------------
#sensor:

###### INPUT BOOLEANS ------------------------------------------
#input_boolean:

###### INPUT SELECT ------------------------------------------
input_select:
  theater_screen:
    name: 'Theater Screen'
    options:
      - open
      - opening
      - closing
      - closed

###### AUTOMATIONS --------------------------------------
automation:
- alias: Theater Screen Open Full Motion
  trigger:
  - platform: state
    entity_id: input_select.theater_screen
    to: "opening"
    for: "00:00:09"
  condition: []
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.theater_screen
      option: open
- alias: Theater Screen Closed Full Motion
  trigger:
  - platform: state
    entity_id: input_select.theater_screen
    to: "closing"
    for: "00:00:09"
  condition: []
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.theater_screen
      option: closed

- alias: Theater Screen Open Tracking
  trigger:
  - platform: state
    entity_id: cover.theater_screen
    to: "open"
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.theater_screen
      option: open
- alias: Theater Screen Closed Tracking
  trigger:
  - platform: state
    entity_id: cover.theater_screen
    to: "closed"
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.theater_screen
      option: closed

###### SCRIPTS ------------------------------------------
script:
  theater_screen_close:
    sequence:
      - service: switch.turn_on
        data:
          entity_id: switch.relay_theater_screen_up
      - service: input_select.select_option
        data:
          entity_id: input_select.theater_screen
          option: closing
      - service: switch.turn_off
        data:
          entity_id: switch.relay_theater_screen_up
  theater_screen_open:
    sequence:
      - service: script.turn_on
        data_template:
          entity_id: >
            {% if is_state("input_select.theater_shade_roman", "open") %}
              script.theater_screen_open_roman_delay_9
            {% elif is_state("input_select.theater_shade_roman", "opening") %}
              script.theater_screen_open_roman_delay_9
            {% elif is_state("input_select.theater_shade_roman", "favorite") %}
              script.theater_screen_open_roman_delay_2
            {% elif is_state("input_select.theater_shade_roman", "closing") %}
              script.theater_screen_open_roman_delay_2
            {% else %}
              script.theater_screen_open_roman_delay_0
            {% endif %}
      - service: switch.turn_on
        data:
          entity_id: switch.relay_theater_screen_down
      - service: input_select.select_option
        data:
          entity_id: input_select.theater_screen
          option: opening
      - service: switch.turn_off
        data:
          entity_id: switch.relay_theater_screen_down

  theater_screen_open_roman_delay_9:
    sequence:
      - service: cover.close_cover
        data:
          entity_id: cover.theater_shade_roman
      - delay:
          seconds: 9
  theater_screen_open_roman_delay_2:
    sequence:
      - service: cover.close_cover
        data:
          entity_id: cover.theater_shade_roman
      - delay:
          seconds: 2
  theater_screen_open_roman_delay_0:
    sequence:
      - service: cover.close_cover
        data:
          entity_id: cover.theater_shade_roman
