
cover:
  - platform: template
    covers:
      projector_screen:
#        device_class:
        friendly_name: "Projector Screen"
        optimistic: true
        open_cover:
          service: script.theater_screen_down
        close_cover:
          service: script.theater_screen_up

###### SENSOR TEMPLATES ------------------------------------------
#sensor:

###### INPUT BOOLEANS ------------------------------------------
#input_boolean:

###### INPUT SELECT ------------------------------------------
input_select:
  theater_screen:
    name: 'Theater Screen'
    options:
      - up
      - raising
      - lowering
      - down


###### AUTOMATIONS --------------------------------------
automation:
- alias: Theater Screen Open
  trigger:
  - platform: state
    entity_id: input_select.theater_screen
    to: "raising"
    for: "00:00:07"
  condition:
  - condition: template
    value_template: "{{ trigger.from_state.state != 'down' }}"
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.theater_screen
      option: up
- alias: Theater Screen Closed
  trigger:
  - platform: state
    entity_id: input_select.theater_screen
    to: "lowering"
    for: "00:00:07"
  condition:
  - condition: template
    value_template: "{{ trigger.from_state.state != 'up' }}"
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.theater_screen
      option: down
- alias: Theater Screen Open Full Motion
  trigger:
  - platform: state
    entity_id: input_select.theater_screen
    to: "raising"
    for: "00:00:14"
  condition: []
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.theater_screen
      option: up
- alias: Theater Screen Closed Full Motion
  trigger:
  - platform: state
    entity_id: input_select.theater_screen
    to: "lowering"
    for: "00:00:14"
  condition: []
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.theater_screen
      option: down

###### SCRIPTS ------------------------------------------
script:
  theater_screen_up:
    sequence:
      - service: switch.turn_on
        data:
          entity_id: switch.relay_theater_screen_up
      - service: input_select.select_option
        data:
          entity_id: input_select.theater_screen
          option: raising
      - service: switch.turn_off
        data:
          entity_id: switch.relay_theater_screen_up
  theater_screen_down:
    sequence:
      - service: cover.close_cover
        data:
          entity_id: cover.theater_roman
      - service: switch.turn_on
        data:
          entity_id: switch.relay_theater_screen_down
      - service: input_select.select_option
        data:
          entity_id: input_select.theater_screen
          option: lowering
      - service: switch.turn_off
        data:
          entity_id: switch.relay_theater_screen_down
