
###### AUTOMATIONS --------------------------------------
automation:

- alias: pico_bed3_keypad_button1
  trigger:
  - entity_id: sensor.bed3_keypad
    platform: state
    to: "1"
  condition: []
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.pico_bed3_keypad_button1
  - delay: '00:00:01'
  - service: switch.turn_off
    target:
      entity_id: switch.pico_bed3_keypad_button1

- alias: pico_bed3_keypad_button2
  trigger:
  - entity_id: sensor.bed3_keypad
    platform: state
    to: "2"
  condition: []
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.pico_bed3_keypad_button2
  - delay: '00:00:01'
  - service: switch.turn_off
    target:
      entity_id: switch.pico_bed3_keypad_button2

- alias: pico_bed3_keypad_button4
  trigger:
  - entity_id: sensor.bed3_keypad
    platform: state
    to: "4"
  condition: []
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.pico_bed3_keypad_button4
  - delay: '00:00:01'
  - service: switch.turn_off
    target:
      entity_id: switch.pico_bed3_keypad_button4

- alias: pico_bed3_keypad_button8
  trigger:
  - entity_id: sensor.bed3_keypad
    platform: state
    to: "8"
  condition: []
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.pico_bed3_keypad_button8
  - delay: '00:00:01'
  - service: switch.turn_off
    target:
      entity_id: switch.pico_bed3_keypad_button8

###### Switch Templates --------------------------------------

switch:
  - platform: template
    switches:
      pico_bed3_keypad_button1:
        turn_on:
          service: switch.turn_on
          target:
            entity_id: switch.pico_bed3_keypad_button1
        turn_off:
          service: switch.turn_off
          target:
            entity_id: switch.pico_bed3_keypad_button1

      pico_bed3_keypad_button2:
        turn_on:
          service: switch.turn_on
          target:
            entity_id: switch.pico_bed3_keypad_button2
        turn_off:
          service: switch.turn_off
          target:
            entity_id: switch.pico_bed3_keypad_button2

      pico_bed3_keypad_button4:
        turn_on:
          service: switch.turn_on
          target:
            entity_id: switch.pico_bed3_keypad_button4
        turn_off:
          service: switch.turn_off
          target:
            entity_id: switch.pico_bed3_keypad_button4

      pico_bed3_keypad_button8:
        turn_on:
          service: switch.turn_on
          target:
            entity_id: switch.pico_bed3_keypad_button8
        turn_off:
          service: switch.turn_off
          target:
            entity_id: switch.pico_bed3_keypad_button8
