
###### INPUT SELECT ------------------------------------------
input_select:

  bed3_light_scene:
    name: 'Bed3 Light Scene'
    options:
      - bright
      - entertain
      - relax
      - 'off'

  bed3_light_scene_relax:
    name: 'Bed3 Light Scene Relax'
    options:
      - reds
      - greens
      - blues
      - yellows
      - whites
      - sunrise
      - sunset
      - custom1
      - custom2
      - custom3

###### AUTOMATIONS --------------------------------------
automation:

- alias: Pico Keypad Bed3 Button 1
  trigger:
  - entity_id: sensor.bed3_keypad
    platform: state
    to: "1"
  condition: []
  action:
  - service: script.bed3_light_scene_bright

- alias: Pico Keypad Bed3 Button 2
  trigger:
  - entity_id: sensor.bed3_keypad
    platform: state
    to: "2"
  condition: []
  action:
  - service: script.bed3_light_scene_entertain

- alias: Pico Keypad Bed3 Button 3
  trigger:
  - entity_id: sensor.bed3_keypad
    platform: state
    to: "4"
  condition: []
  action:
  - service: script.bed3_light_scene_relax

- alias: Pico Keypad Bed3 Button 4
  trigger:
  - entity_id: sensor.bed3_keypad
    platform: state
    to: "8"
  condition: []
  action:
  - service: script.bed3_light_scene_off

- alias: Bed3 Lights Off
  trigger:
  - entity_id: group.lights_bed3
    platform: state
    to: "off"
  condition: []
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.bed3_light_scene
      option: 'off'

###### AUTOMATIONS --------------------------------------
scene:
#   Bed3 Bright
- name: Bed3 Bright
  entities:
    light.lifx1:
      state: on
      brightness: 255
      color_temp: 206
    light.lifx2:
      state: on
      brightness: 255
      color_temp: 206
    light.lifx3:
      state: on
      brightness: 255
      color_temp: 206
    light.lifxmini1:
      state: on
      brightness: 255
#   Bed3 Entertain
- name: Bed3 Entertain
  entities:
    light.lifx1:
      state: on
      brightness: 155
      color_temp: 370
    light.lifx2:
      state: on
      brightness: 155
      color_temp: 370
    light.lifx3:
      state: on
      brightness: 155
      color_temp: 370
    light.lifxmini1:
      state: on
      brightness: 255
#   Bed3 All Off
- name: Bed3 All Off
  entities:
    light.lifx1:
      state: off
    light.lifx2:
      state: off
    light.lifx3:
      state: off
    light.lifxmini1:
      state: off

####   Bed3 Relax Colors
- name: Bed3 Relax Reds
  entities:
    light.lifx1:
      state: on
      brightness: 155
      rgb_color: [255,0,50]
    light.lifx2:
      state: on
      brightness: 120
      rgb_color: [255,30,71]
    light.lifx3:
      state: on
      brightness: 85
      rgb_color: [125,0,150]
    light.lifxmini1:
      state: off
- name: Bed3 Relax Blues
  entities:
    light.lifx1:
      state: on
      brightness: 155
      rgb_color: [28,213,255]
    light.lifx2:
      state: on
      brightness: 120
      rgb_color: [8,0,255]
    light.lifx3:
      state: on
      brightness: 85
      rgb_color: [200,186,255]
    light.lifxmini1:
      state: off
- name: Bed3 Relax Greens
  entities:
    light.lifx1:
      state: on
      brightness: 155
      rgb_color: [32,255,21]
    light.lifx2:
      state: on
      brightness: 120
      rgb_color: [188,255,124]
    light.lifx3:
      state: on
      brightness: 85
      rgb_color: [0,255,51]
    light.lifxmini1:
      state: off
- name: Bed3 Relax Yellows
  entities:
    light.lifx1:
      state: on
      brightness: 155
      rgb_color: [255,188,63]
    light.lifx2:
      state: on
      brightness: 120
      rgb_color: [255,188,63]
    light.lifx3:
      state: on
      brightness: 85
      rgb_color: [255,166,50]
    light.lifxmini1:
      state: off
- name: Bed3 Relax Whites
  entities:
    light.lifx1:
      state: on
      brightness: 155
      color_temp: 666
    light.lifx2:
      state: on
      brightness: 120
      color_temp: 400
    light.lifx3:
      state: on
      brightness: 85
      color_temp: 200
    light.lifxmini1:
      state: off
- name: Bed3 Relax Sunrise
  entities:
    light.lifx1:
      state: on
      brightness: 85
      rgb_color: [79,154,218]
    light.lifx2:
      state: on
      brightness: 100
      rgb_color: [252,213,150]
    light.lifx3:
      state: on
      brightness: 125
      rgb_color: [253,212,0]
    light.lifxmini1:
      state: off
- name: Bed3 Relax Sunset
  entities:
    light.lifx1:
      state: on
      brightness: 70
      rgb_color: [35,21,89]
    light.lifx2:
      state: on
      brightness: 95
      rgb_color: [242,34,37]
    light.lifx3:
      state: on
      brightness: 125
      rgb_color: [252,94,1]
    light.lifxmini1:
      state: off


###### SCRIPT ------------------------------------------
script:

  bed3_light_scene_bright:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.bed3_light_scene
          option: bright
      - service: scene.turn_on
        target:
          entity_id: scene.bed3_bright
        data:
          transition: 3

  bed3_light_scene_entertain:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.bed3_light_scene
          option: entertain
      - service: scene.turn_on
        target:
          entity_id: scene.bed3_entertain
        data:
          transition: 3

  bed3_light_scene_off:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.bed3_light_scene
          option: 'off'
      - service: scene.turn_on
        target:
          entity_id: scene.bed3_all_off
        data:
          transition: 3


### Relax Scene Options
  bed3_light_scene_relax:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.bed3_light_scene
          option: relax
      - service: script.turn_on
        data_template:
          entity_id: >
            {% if is_state("input_select.bed3_light_scene_relax", "reds") %}
              script.bed3_light_scene_relax_reds
            {% elif is_state("input_select.bed3_light_scene_relax", "greens") %}
              script.bed3_light_scene_relax_greens
            {% elif is_state("input_select.bed3_light_scene_relax", "blues") %}
              script.bed3_light_scene_relax_blues
            {% elif is_state("input_select.bed3_light_scene_relax", "yellows") %}
              script.bed3_light_scene_relax_yellows
            {% elif is_state("input_select.bed3_light_scene_relax", "sunrise") %}
              script.bed3_light_scene_relax_sunrise
            {% elif is_state("input_select.bed3_light_scene_relax", "sunset") %}
              script.bed3_light_scene_relax_sunset
            {% elif is_state("input_select.bed3_light_scene_relax", "custom1") %}
              script.bed3_light_scene_relax_custom1
            {% elif is_state("input_select.bed3_light_scene_relax", "custom2") %}
              script.bed3_light_scene_relax_custom2
            {% elif is_state("input_select.bed3_light_scene_relax", "custom3") %}
              script.bed3_light_scene_relax_custom3
            {% else %}
              script.bed3_light_scene_relax_whites
            {% endif %}

  bed3_light_scene_relax_reds:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.bed3_light_scene_relax
          option: reds
      - service: scene.turn_on
        target:
          entity_id: scene.bed3_relax_reds
        data:
          transition: 3

  bed3_light_scene_relax_blues:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.bed3_light_scene_relax
          option: blues
      - service: scene.turn_on
        target:
          entity_id: scene.bed3_relax_blues
        data:
          transition: 3

  bed3_light_scene_relax_greens:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.bed3_light_scene_relax
          option: greens
      - service: scene.turn_on
        target:
          entity_id: scene.bed3_relax_greens
        data:
          transition: 3

  bed3_light_scene_relax_yellows:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.bed3_light_scene_relax
          option: yellows
      - service: scene.turn_on
        target:
          entity_id: scene.bed3_relax_yellows
        data:
          transition: 3

  bed3_light_scene_relax_whites:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.bed3_light_scene_relax
          option: whites
      - service: scene.turn_on
        target:
          entity_id: scene.bed3_relax_whites
        data:
          transition: 3

# Suns
  bed3_light_scene_relax_sunrise:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.bed3_light_scene_relax
          option: sunrise
      - service: scene.turn_on
        target:
          entity_id: scene.bed3_relax_sunrise
        data:
          transition: 3

  bed3_light_scene_relax_sunset:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.bed3_light_scene_relax
          option: sunset
      - service: scene.turn_on
        target:
          entity_id: scene.bed3_relax_sunset
        data:
          transition: 3

# Customs

  bed3_light_scene_relax_custom1:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.bed3_light_scene_relax
          option: custom1
      - service: scene.turn_on
        target:
          entity_id: scene.bed3_relax_custom1
        data:
          transition: 3

  bed3_light_scene_relax_custom1_create:
    sequence:
      - service: scene.create
        data:
          scene_id: bed3_relax_custom1
          snapshot_entities:
          - light.lifx1
          - light.lifx2
          - light.lifx3
          - light.lifxmini1
      - service: input_select.select_option
        data:
          entity_id: input_select.bed3_light_scene_relax
          option: custom1

  bed3_light_scene_relax_custom2:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.bed3_light_scene_relax
          option: custom2
      - service: scene.turn_on
        target:
          entity_id: scene.bed3_relax_custom2
        data:
          transition: 3

  bed3_light_scene_relax_custom2_create:
    sequence:
      - service: scene.create
        data:
          scene_id: bed3_relax_custom2
          snapshot_entities:
          - light.lifx1
          - light.lifx2
          - light.lifx3
          - light.lifxmini1
      - service: input_select.select_option
        data:
          entity_id: input_select.bed3_light_scene_relax
          option: custom2

  bed3_light_scene_relax_custom3:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.bed3_light_scene_relax
          option: custom3
      - service: scene.turn_on
        target:
          entity_id: scene.bed3_relax_custom3
        data:
          transition: 3

  bed3_light_scene_relax_custom3_create:
    sequence:
      - service: scene.create
        data:
          scene_id: bed3_relax_custom3
          snapshot_entities:
          - light.lifx1
          - light.lifx2
          - light.lifx3
          - light.lifxmini1
      - service: input_select.select_option
        data:
          entity_id: input_select.bed3_light_scene_relax
          option: custom3

# Set Customs on Startup
  bed3_light_scene_relax_custom_set:
    sequence:
      - service: scene.create
        data:
          scene_id: bed3_relax_custom1
          entities:
            light.lifx1:
              state: "on"
              brightness: 155
              rgb_color: [127,255,127]
            light.lifx2:
              state: "on"
              brightness: 115
              rgb_color: [131,0,255]
            light.lifx3:
              state: "on"
              brightness: 75
              rgb_color: [38,128,255]
            light.lifxmini1:
              state: "off"
      - service: scene.create
        data:
          scene_id: bed3_relax_custom2
          entities:
            light.lifx1:
              state: "on"
              brightness: 155
              rgb_color: [6,2,255]
            light.lifx2:
              state: "on"
              brightness: 115
              rgb_color: [214,225,255]
            light.lifx3:
              state: "on"
              brightness: 75
              rgb_color: [255,195,43]
            light.lifxmini1:
              state: "off"
      - service: scene.create
        data:
          scene_id: bed3_relax_custom3
          entities:
            light.lifx1:
              state: "on"
              brightness: 155
              rgb_color: [250,255,242]
            light.lifx2:
              state: "on"
              brightness: 115
              rgb_color: [255,193,239]
            light.lifx3:
              state: "on"
              brightness: 75
              rgb_color: [255,175,177]
            light.lifxmini1:
              state: "off"
