
###### INPUT SELECT ------------------------------------------
input_select:

  bed3_light_scene:
    name: 'Bed3 Light Scene'
    options:
      - bright
      - entertain
      - relax
      - 'off'

  bed3_light_scene_relax:
    name: 'Bed3 Light Scene Relax'
    options:
      - reds
      - greens
      - blues
      - whites

  bed3_light_scene_relax_brightness:
    name: 'Bed3 Light Scene Relax Brightness'
    options:
      - level1
      - level2
      - level3
      - level4

###### AUTOMATIONS --------------------------------------
automation:

- alias: Pico Keypad Bed3 Button 1
  trigger:
  - entity_id: sensor.bed3_keypad
    platform: state
    to: "1"
  condition: []
  action:
  - service: script.bed3_light_scene_bright

- alias: Pico Keypad Bed3 Button 2
  trigger:
  - entity_id: sensor.bed3_keypad
    platform: state
    to: "2"
  condition: []
  action:
  - service: script.bed3_light_scene_entertain

- alias: Pico Keypad Bed3 Button 3
  trigger:
  - entity_id: sensor.bed3_keypad
    platform: state
    to: "4"
  condition: []
  action:
  - service: script.bed3_light_scene_relax

- alias: Pico Keypad Bed3 Button 4
  trigger:
  - entity_id: sensor.bed3_keypad
    platform: state
    to: "8"
  condition: []
  action:
  - service: script.bed3_light_scene_off

- alias: Bed3 Lights Off
  trigger:
  - entity_id: group.lights_bed3
    platform: state
    to: "off"
  condition: []
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.bed3_light_scene
      option: 'off'

###### SCENES --------------------------------------
scene:
#   Bed3 Bright
- name: Bed3 Bright
  entities:
    light.lifx1:
      state: on
      brightness: 255
      color_temp: 206
    light.lifx2:
      state: on
      brightness: 255
      color_temp: 206
    light.lifx3:
      state: on
      brightness: 255
      color_temp: 206
    light.lifxmini1:
      state: on
      brightness: 255
#   Bed3 Entertain
- name: Bed3 Entertain
  entities:
    light.lifx1:
      state: on
      brightness: 155
      color_temp: 370
    light.lifx2:
      state: on
      brightness: 155
      color_temp: 370
    light.lifx3:
      state: on
      brightness: 155
      color_temp: 370
    light.lifxmini1:
      state: on
      brightness: 255
#   Bed3 All Off
- name: Bed3 All Off
  entities:
    light.lifx1:
      state: off
    light.lifx2:
      state: off
    light.lifx3:
      state: off
    light.lifxmini1:
      state: off

####   Bed3 Relax Colors
- name: Bed3 Relax Reds
  entities:
    light.lifx1:
      state: on
      brightness: 1
      rgb_color: [255,0,50]
    light.lifx2:
      state: on
      brightness: 1
      rgb_color: [255,30,71]
    light.lifx3:
      state: on
      brightness: 1
      rgb_color: [125,0,150]
    light.lifxmini1:
      state: off
- name: Bed3 Relax Blues
  entities:
    light.lifx1:
      state: on
      brightness: 1
      rgb_color: [28,213,255]
    light.lifx2:
      state: on
      brightness: 1
      rgb_color: [8,0,255]
    light.lifx3:
      state: on
      brightness: 1
      rgb_color: [200,186,255]
    light.lifxmini1:
      state: off
- name: Bed3 Relax Greens
  entities:
    light.lifx1:
      state: on
      brightness: 1
      rgb_color: [32,255,21]
    light.lifx2:
      state: on
      brightness: 1
      rgb_color: [188,255,124]
    light.lifx3:
      state: on
      brightness: 1
      rgb_color: [0,255,51]
    light.lifxmini1:
      state: off
- name: Bed3 Relax Whites
  entities:
    light.lifx1:
      state: on
      brightness: 1
      color_temp: 666
    light.lifx2:
      state: on
      brightness: 1
      color_temp: 400
    light.lifx3:
      state: on
      brightness: 1
      color_temp: 200
    light.lifxmini1:
      state: off

###### SCRIPT ------------------------------------------
script:

  bed3_light_scene_bright:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.bed3_light_scene
          option: bright
      - service: scene.turn_on
        target:
          entity_id: scene.bed3_bright
        data:
          transition: 3

  bed3_light_scene_entertain:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.bed3_light_scene
          option: entertain
      - service: scene.turn_on
        target:
          entity_id: scene.bed3_entertain
        data:
          transition: 3

  bed3_light_scene_off:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.bed3_light_scene
          option: 'off'
      - service: scene.turn_on
        target:
          entity_id: scene.bed3_all_off
        data:
          transition: 3


### Relax Scene Options
  bed3_light_scene_relax:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.bed3_light_scene
          option: relax
      - service: script.turn_on
        data_template:
          entity_id: >
            {% if is_state("input_select.bed3_light_scene_relax", "reds") %}
              script.bed3_light_scene_relax_reds
            {% elif is_state("input_select.bed3_light_scene_relax", "greens") %}
              script.bed3_light_scene_relax_greens
            {% elif is_state("input_select.bed3_light_scene_relax", "blues") %}
              script.bed3_light_scene_relax_blues
            {% else %}
              script.bed3_light_scene_relax_whites
            {% endif %}

  bed3_light_scene_relax_reds:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.bed3_light_scene_relax
          option: reds
      - service: input_select.select_option
        data:
          entity_id: input_select.bed3_light_scene_relax_brightness
          option: level1
      - service: scene.turn_on
        target:
          entity_id: scene.bed3_relax_reds
        data:
          transition: 3

  bed3_light_scene_relax_blues:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.bed3_light_scene_relax
          option: blues
      - service: input_select.select_option
        data:
          entity_id: input_select.bed3_light_scene_relax_brightness
          option: level1
      - service: scene.turn_on
        target:
          entity_id: scene.bed3_relax_blues
        data:
          transition: 3

  bed3_light_scene_relax_greens:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.bed3_light_scene_relax
          option: greens
      - service: input_select.select_option
        data:
          entity_id: input_select.bed3_light_scene_relax_brightness
          option: level1
      - service: scene.turn_on
        target:
          entity_id: scene.bed3_relax_greens
        data:
          transition: 3

  bed3_light_scene_relax_whites:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.bed3_light_scene_relax
          option: whites
      - service: input_select.select_option
        data:
          entity_id: input_select.bed3_light_scene_relax_brightness
          option: level1
      - service: scene.turn_on
        target:
          entity_id: scene.bed3_relax_whites
        data:
          transition: 3

# Brightness

  bed3_light_scene_relax_brightness1:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.bed3_light_scene_relax_brightness
          option: level1
      - service: light.turn_on
        target:
          entity_id:
            - light.lifx1
            - light.lifx2
            - light.lifx3
        data:
          brightness: 1
          transition: 1

  bed3_light_scene_relax_brightness2:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.bed3_light_scene_relax_brightness
          option: level2
      - service: light.turn_on
        target:
          entity_id:
            - light.lifx1
            - light.lifx2
            - light.lifx3
        data:
          brightness: 20
          transition: 1

  bed3_light_scene_relax_brightness3:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.bed3_light_scene_relax_brightness
          option: level3
      - service: light.turn_on
        target:
          entity_id:
            - light.lifx1
            - light.lifx2
            - light.lifx3
        data:
          brightness: 60
          transition: 1

  bed3_light_scene_relax_brightness4:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.bed3_light_scene_relax_brightness
          option: level4
      - service: light.turn_on
        target:
          entity_id:
            - light.lifx1
            - light.lifx2
            - light.lifx3
        data:
          brightness: 80
          transition: 1
