
###### INPUT SELECT ------------------------------------------
input_select:

  living_light_scene:
    name: 'Living Light Scene'
    options:
      - bright
      - entertain
      - relax
      - 'off'

###### AUTOMATIONS --------------------------------------
automation:

- alias: Pico Keypad Living Button 1 New
  description: 'Living First Button Pressed'
  mode: single
  trigger:
    - platform: device
      device_id: e66b2a3e377181b497340dc9826cc5fa
      domain: lutron_caseta
      type: press
      subtype: button_1
  condition: []
  action:
    - service: script.living_light_scene_bright

- alias: Pico Keypad Living Button 1
  trigger:
  - entity_id: sensor.living_room_keypad
    platform: state
    to: "1"
  condition: []
  action:
  - service: script.living_light_scene_bright

- alias: Pico Keypad Kitchen Button 1 Hold
  trigger:
  - entity_id: sensor.living_room_keypad
    platform: state
    to: "1"
    for: "00:00:02"
  condition: []
  action:
  - service: script.mode_hunt_start

- alias: Pico Keypad Living Button 2
  trigger:
  - entity_id: sensor.living_room_keypad
    platform: state
    to: "2"
  condition: []
  action:
  - service: script.living_light_scene_entertain

- alias: Pico Keypad Living Button 3
  trigger:
  - entity_id: sensor.living_room_keypad
    platform: state
    to: "4"
  condition: []
  action:
  - service: script.living_light_scene_relax

- alias: Pico Keypad Living Button 4
  trigger:
  - entity_id: sensor.living_room_keypad
    platform: state
    to: "8"
  - entity_id: group.lights_living
    platform: state
    to: "off"
  condition: []
  action:
  - service: script.living_light_scene_off

- alias: Pico Keypad Kitchen Button 4 Hold
  trigger:
  - entity_id: sensor.living_room_keypad
    platform: state
    to: "8"
    for: "00:00:02"
  condition: []
  action:
  - service: script.mode_hunt_end

- alias: Living Lights Off
  trigger:
  - entity_id: group.lights_living
    platform: state
    to: "off"
  condition: []
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.living_light_scene
      option: 'off'

###### SCRIPT ------------------------------------------
script:

  living_light_scene_bright:
    sequence:
      - service: scene.turn_on
        target:
          entity_id: scene.living_bright
      - service: input_select.select_option
        data:
          entity_id: input_select.living_light_scene
          option: bright
  living_light_scene_entertain:
    sequence:
      - service: scene.turn_on
        target:
          entity_id: scene.living_entertain
      - service: input_select.select_option
        data:
          entity_id: input_select.living_light_scene
          option: entertain
  living_light_scene_relax:
    sequence:
      - service: scene.turn_on
        target:
          entity_id: scene.living_relax
      - service: input_select.select_option
        data:
          entity_id: input_select.living_light_scene
          option: relax
      - service: input_select.select_option
        data:
          entity_id: input_select.living_light_scene
          option: relax
  living_light_scene_off:
    sequence:
      - service: scene.turn_on
        target:
          entity_id: scene.living_all_off
      - service: input_select.select_option
        data:
          entity_id: input_select.living_light_scene
          option: 'off'
