
###### INPUT SELECT ------------------------------------------
input_select:

  master_light_scene:
    name: 'Master Light Scene'
    options:
      - bright
      - entertain
      - 'relax'
      - 'off'

  master_light_scene_relax:
    name: 'Master Light Scene Relax'
    options:
      - reds
      - greens
      - blues
      - yellows
      - whites
      - sunrise
      - sunset
      - custom1
      - custom2
      - custom3

###### AUTOMATIONS --------------------------------------
automation:

- alias: Pico Keypad Master Button 1
  trigger:
  - entity_id:
      - sensor.master_bedroom_keypad
      - sensor.master_bedroom_keypad_his
      - sensor.master_bedroom_keypad_her
    platform: state
    to: "1"
  condition: []
  action:
  - service: script.master_light_scene_bright
- alias: Pico Keypad Master Button 2
  trigger:
  - entity_id:
      - sensor.master_bedroom_keypad
      - sensor.master_bedroom_keypad_his
      - sensor.master_bedroom_keypad_her
    platform: state
    to: "2"
  condition: []
  action:
  - service: script.master_light_scene_entertain
- alias: Pico Keypad Master Button 3
  trigger:
  - entity_id:
      - sensor.master_bedroom_keypad
      - sensor.master_bedroom_keypad_his
      - sensor.master_bedroom_keypad_her
    platform: state
    to: "4"
  condition: []
  action:
  - service: script.master_light_scene_relax
- alias: Pico Keypad Master Button 4
  trigger:
  - entity_id:
      - sensor.master_bedroom_keypad
      - sensor.master_bedroom_keypad_his
      - sensor.master_bedroom_keypad_her
    platform: state
    to: "8"
  condition: []
  action:
  - service: script.master_light_scene_off

- alias: Master Lights Off
  trigger:
  - entity_id: group.lights_master
    platform: state
    to: "off"
  condition: []
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.master_light_scene
      option: 'off'

###### SCRIPT ------------------------------------------
script:

  master_light_scene_bright:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.master_light_scene
          option: bright
      - service: scene.turn_on
        target:
          entity_id: scene.master_bright
        data:
          transition: 3
  master_light_scene_entertain:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.master_light_scene
          option: entertain
      - service: scene.turn_on
        target:
          entity_id: scene.master_entertain
        data:
          transition: 3
  master_light_scene_off:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.master_light_scene
          option: 'off'
      - service: scene.turn_on
        target:
          entity_id: scene.master_all_off
        data:
          transition: 3

### Relax Scene
  master_light_scene_relax:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.master_light_scene
          option: relax
      - service: script.turn_on
        data_template:
          entity_id: >
            {% if is_state("input_select.master_light_scene_relax", "reds") %}
              script.master_light_scene_relax_reds
            {% elif is_state("input_select.master_light_scene_relax", "greens") %}
              script.master_light_scene_relax_greens
            {% elif is_state("input_select.master_light_scene_relax", "blues") %}
              script.master_light_scene_relax_blues
            {% elif is_state("input_select.master_light_scene_relax", "yellows") %}
              script.master_light_scene_relax_yellows
            {% elif is_state("input_select.master_light_scene_relax", "sunrise") %}
              script.master_light_scene_relax_sunrise
            {% elif is_state("input_select.master_light_scene_relax", "sunset") %}
              script.master_light_scene_relax_sunset
            {% elif is_state("input_select.master_light_scene_relax", "custom1") %}
              script.master_light_scene_relax_custom1
            {% elif is_state("input_select.master_light_scene_relax", "custom2") %}
              script.master_light_scene_relax_custom2
            {% elif is_state("input_select.master_light_scene_relax", "custom3") %}
              script.master_light_scene_relax_custom3
            {% else %}
              script.master_light_scene_relax_whites
            {% endif %}

  master_light_scene_relax_reds:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.master_light_scene_relax
          option: reds
      - service: scene.turn_on
        target:
          entity_id: scene.master_relax_reds
        data:
          transition: 3

  master_light_scene_relax_blues:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.master_light_scene_relax
          option: blues
      - service: scene.turn_on
        target:
          entity_id: scene.master_relax_blues
        data:
          transition: 3

  master_light_scene_relax_greens:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.master_light_scene_relax
          option: greens
      - service: scene.turn_on
        target:
          entity_id: scene.master_relax_greens
        data:
          transition: 3

  master_light_scene_relax_yellows:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.master_light_scene_relax
          option: yellows
      - service: scene.turn_on
        target:
          entity_id: scene.master_relax_yellows
        data:
          transition: 3

  master_light_scene_relax_whites:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.master_light_scene_relax
          option: whites
      - service: scene.turn_on
        target:
          entity_id: scene.master_relax_whites
        data:
          transition: 3

# Suns
  master_light_scene_relax_sunrise:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.master_light_scene_relax
          option: sunrise
      - service: scene.turn_on
        target:
          entity_id: scene.master_relax_sunrise
        data:
          transition: 3

  master_light_scene_relax_sunset:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.master_light_scene_relax
          option: sunset
      - service: scene.turn_on
        target:
          entity_id: scene.master_relax_sunset
        data:
          transition: 3

# Customs

  master_light_scene_relax_custom1:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.master_light_scene_relax
          option: custom1
      - service: scene.turn_on
        target:
          entity_id: scene.master_relax_custom1
        data:
          transition: 3

  master_light_scene_relax_custom1_create:
    sequence:
      - service: scene.create
        data:
          scene_id: master_relax_custom1
          snapshot_entities:
          - light.lifx5
          - light.lifx6
          - light.master_bedroom_ceiling_fan_light
          - light.master_bedroom_entry
      - service: input_select.select_option
        data:
          entity_id: input_select.master_light_scene_relax
          option: custom1

  master_light_scene_relax_custom2:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.master_light_scene_relax
          option: custom2
      - service: scene.turn_on
        target:
          entity_id: scene.master_relax_custom2
        data:
          transition: 3

  master_light_scene_relax_custom2_create:
    sequence:
      - service: scene.create
        data:
          scene_id: master_relax_custom2
          snapshot_entities:
          - light.lifx5
          - light.lifx6
          - light.master_bedroom_ceiling_fan_light
          - light.master_bedroom_entry
      - service: input_select.select_option
        data:
          entity_id: input_select.master_light_scene_relax
          option: custom2

  master_light_scene_relax_custom3:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.master_light_scene_relax
          option: custom3
      - service: scene.turn_on
        target:
          entity_id: scene.master_relax_custom3
        data:
          transition: 3

  master_light_scene_relax_custom3_create:
    sequence:
      - service: scene.create
        data:
          scene_id: master_relax_custom3
          snapshot_entities:
          - light.lifx5
          - light.lifx6
          - light.master_bedroom_ceiling_fan_light
          - light.master_bedroom_entry
      - service: input_select.select_option
        data:
          entity_id: input_select.master_light_scene_relax
          option: custom3

# Set Customs on Startup
  master_light_scene_relax_custom_set:
    sequence:
      - service: scene.create
        data:
          scene_id: master_relax_custom1
          entities:
            light.lifx5:
              state: "on"
              brightness: 1
              rgb_color: [127,255,127]
            light.lifx6:
              state: "on"
              brightness: 1
              rgb_color: [131,0,255]
            light.master_bedroom_ceiling_fan_light:
              state: "off"
            light.master_bedroom_entry:
              state: "off"
      - service: scene.create
        data:
          scene_id: master_relax_custom2
          entities:
            light.lifx5:
              state: "on"
              brightness: 1
              rgb_color: [27,155,227]
            light.lifx6:
              state: "on"
              brightness: 1
              rgb_color: [231,210,55]
            light.master_bedroom_ceiling_fan_light:
              state: "off"
            light.master_bedroom_entry:
              state: "off"
      - service: scene.create
        data:
          scene_id: master_relax_custom3
          entities:
            light.lifx5:
              state: "on"
              brightness: 1
              rgb_color: [227,55,27]
            light.lifx6:
              state: "on"
              brightness: 1
              rgb_color: [31,130,125]
            light.master_bedroom_ceiling_fan_light:
              state: "off"
            light.master_bedroom_entry:
              state: "off"
