
###### INPUT SELECT ------------------------------------------
input_select:

  master_light_scene:
    name: 'Master Light Scene'
    options:
      - bright
      - entertain
      - 'relax'
      - 'off'

  master_light_scene_relax:
    name: 'Master Light Scene Relax'
    options:
      - reds
      - greens
      - blues
      - whites

  master_light_scene_relax_brightness:
    name: 'Master Light Scene Relax Brightness'
    options:
      - level1
      - level2
      - level3
      - level4

###### AUTOMATIONS --------------------------------------
automation:

- alias: Pico Keypad Master Button 1
  trigger:
  - entity_id:
      - sensor.master_bedroom_keypad
      - sensor.master_bedroom_keypad_his
      - sensor.master_bedroom_keypad_her
    platform: state
    to: "1"
  condition: []
  action:
  - service: script.master_light_scene_bright

- alias: Pico Keypad Master Button 2
  trigger:
  - entity_id:
      - sensor.master_bedroom_keypad
      - sensor.master_bedroom_keypad_his
      - sensor.master_bedroom_keypad_her
    platform: state
    to: "2"
  condition: []
  action:
  - service: script.master_light_scene_entertain

- alias: Pico Keypad Master Button 3
  trigger:
  - entity_id:
      - sensor.master_bedroom_keypad
      - sensor.master_bedroom_keypad_his
      - sensor.master_bedroom_keypad_her
    platform: state
    to: "4"
  condition: []
  action:
  - service: script.master_light_scene_relax

- alias: Pico Keypad Master Button 4
  trigger:
  - entity_id:
      - sensor.master_bedroom_keypad
      - sensor.master_bedroom_keypad_his
      - sensor.master_bedroom_keypad_her
    platform: state
    to: "8"
  condition: []
  action:
  - service: script.master_light_scene_off

- alias: Master Lights Off
  trigger:
  - entity_id: group.lights_master
    platform: state
    to: "off"
  condition: []
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.master_light_scene
      option: 'off'

###### SCENES --------------------------------------
scene:
#   Master Bright
- name: Master Bright
  entities:
    light.master_bedroom_entry:
      state: on
    light.master_bedroom_ceiling_fan_light:
      state: on
    light.lifx5:
      state: on
      brightness: 101
      color_temp: 370
    light.lifx6:
      state: on
      brightness: 101
      color_temp: 370
#   Master Entertain
- name: Master Entertain
  entities:
    light.master_bedroom_entry:
      state: on
      brightness: 102
    light.master_bedroom_ceiling_fan_light:
      state: on
      brightness: 76
    light.lifx5:
      state: off
    light.lifx6:
      state: off
#   Master All Off
- name: Master All Off
  entities:
    light.master_bedroom_entry:
      state: off
    light.master_bedroom_ceiling_fan_light:
      state: off
    light.lifx5:
      state: off
    light.lifx6:
      state: off
####   Master Relax Colors
- name: Master Relax Reds
  entities:
    light.lifx5:
      state: on
      brightness: 1
      rgb_color: [255,30,71]
    light.lifx6:
      state: on
      brightness: 1
      rgb_color: [255,30,71]
    light.master_bedroom_ceiling_fan_light:
      state: off
    light.master_bedroom_entry:
      state: off
- name: Master Relax Blues
  entities:
    light.lifx5:
      state: on
      brightness: 1
      rgb_color: [8,0,255]
    light.lifx6:
      state: on
      brightness: 1
      rgb_color: [8,0,255]
    light.master_bedroom_ceiling_fan_light:
      state: off
    light.master_bedroom_entry:
      state: off
- name: Master Relax Greens
  entities:
    light.lifx5:
      state: on
      brightness: 1
      rgb_color: [32,255,21]
    light.lifx6:
      state: on
      brightness: 1
      rgb_color: [32,255,21]
    light.master_bedroom_ceiling_fan_light:
      state: off
    light.master_bedroom_entry:
      state: off
- name: Master Relax Whites
  entities:
    light.lifx5:
      state: on
      brightness: 1
      color_temp: 666
    light.lifx6:
      state: on
      brightness: 1
      color_temp: 666
    light.master_bedroom_ceiling_fan_light:
      state: off
    light.master_bedroom_entry:
      state: off

###### SCRIPT ------------------------------------------
script:

  master_light_scene_bright:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.master_light_scene
          option: bright
      - service: scene.turn_on
        target:
          entity_id: scene.master_bright
        data:
          transition: 3
  master_light_scene_entertain:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.master_light_scene
          option: entertain
      - service: scene.turn_on
        target:
          entity_id: scene.master_entertain
        data:
          transition: 3
  master_light_scene_off:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.master_light_scene
          option: 'off'
      - service: scene.turn_on
        target:
          entity_id: scene.master_all_off
        data:
          transition: 3

### Relax Scene
  master_light_scene_relax:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.master_light_scene
          option: relax
      - service: script.turn_on
        data_template:
          entity_id: >
            {% if is_state("input_select.master_light_scene_relax", "reds") %}
              script.master_light_scene_relax_reds
            {% elif is_state("input_select.master_light_scene_relax", "greens") %}
              script.master_light_scene_relax_greens
            {% elif is_state("input_select.master_light_scene_relax", "blues") %}
              script.master_light_scene_relax_blues
            {% else %}
              script.master_light_scene_relax_whites
            {% endif %}

  master_light_scene_relax_reds:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.master_light_scene_relax
          option: reds
      - service: input_select.select_option
        data:
          entity_id: input_select.master_light_scene_relax_brightness
          option: level1
      - service: scene.turn_on
        target:
          entity_id: scene.master_relax_reds
        data:
          transition: 3

  master_light_scene_relax_blues:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.master_light_scene_relax
          option: blues
      - service: input_select.select_option
        data:
          entity_id: input_select.master_light_scene_relax_brightness
          option: level1
      - service: scene.turn_on
        target:
          entity_id: scene.master_relax_blues
        data:
          transition: 3

  master_light_scene_relax_greens:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.master_light_scene_relax
          option: greens
      - service: input_select.select_option
        data:
          entity_id: input_select.master_light_scene_relax_brightness
          option: level1
      - service: scene.turn_on
        target:
          entity_id: scene.master_relax_greens
        data:
          transition: 3

  master_light_scene_relax_whites:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.master_light_scene_relax
          option: whites
      - service: input_select.select_option
        data:
          entity_id: input_select.master_light_scene_relax_brightness
          option: level1
      - service: scene.turn_on
        target:
          entity_id: scene.master_relax_whites
        data:
          transition: 3

# Brightness

  master_light_scene_relax_brightness1:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.master_light_scene_relax_brightness
          option: level1
      - service: light.turn_on
        target:
          entity_id:
            - light.lifx5
            - light.lifx6
        data:
          brightness: 1
          transition: 1

  master_light_scene_relax_brightness2:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.master_light_scene_relax_brightness
          option: level2
      - service: light.turn_on
        target:
          entity_id:
            - light.lifx5
            - light.lifx6
        data:
          brightness: 20
          transition: 1

  master_light_scene_relax_brightness3:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.master_light_scene_relax_brightness
          option: level3
      - service: light.turn_on
        target:
          entity_id:
            - light.lifx5
            - light.lifx6
        data:
          brightness: 60
          transition: 1

  master_light_scene_relax_brightness4:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.master_light_scene_relax_brightness
          option: level4
      - service: light.turn_on
        target:
          entity_id:
            - light.lifx5
            - light.lifx6
        data:
          brightness: 80
          transition: 1
