
###### INPUT SELECT ------------------------------------------
input_select:

  master_light_scene:
    name: 'Master Light Scene'
    options:
      - bright
      - entertain
      - relax
      - 'off'

  master_light_scene_relax_brightness:
    name: 'Master Light Scene Relax Brightness'
    options:
      - level1
      - level2
      - level3
      - level4

###### AUTOMATIONS --------------------------------------
automation:

- alias: Pico Keypad Master Button 1
  trigger:
  - entity_id:
      - sensor.master_bedroom_keypad
      - sensor.master_bedroom_keypad_his
      - sensor.master_bedroom_keypad_her
    platform: state
    to: "1"
  condition: []
  action:
  - service: script.master_light_scene_bright

- alias: Pico Keypad Master Button 2
  trigger:
  - entity_id:
      - sensor.master_bedroom_keypad
      - sensor.master_bedroom_keypad_his
      - sensor.master_bedroom_keypad_her
    platform: state
    to: "2"
  condition: []
  action:
  - service: script.master_light_scene_entertain

- alias: Pico Keypad Master Button 3
  trigger:
  - entity_id:
      - sensor.master_bedroom_keypad
      - sensor.master_bedroom_keypad_his
      - sensor.master_bedroom_keypad_her
    platform: state
    to: "4"
  condition: []
  action:
  - service: script.master_light_scene_relax

- alias: Pico Keypad Master Button 4
  trigger:
  - entity_id:
      - sensor.master_bedroom_keypad
      - sensor.master_bedroom_keypad_his
      - sensor.master_bedroom_keypad_her
    platform: state
    to: "8"
  condition: []
  action:
  - service: script.turn_on
    data_template:
      entity_id: >
        {% if is_state("group.lights_master", "off") %}
          script.master_ledstrip_power_off
        {% else %}
          none
        {% endif %}
  - service: script.master_light_scene_off


- alias: Master Lights Off
  trigger:
  - entity_id: group.lights_master
    platform: state
    to: "off"
  condition: []
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.master_light_scene
      option: 'off'

###### SCENES --------------------------------------
scene:
#   Master Bright
- name: Master Bright
  entities:
    light.master_bedroom_entry:
      state: on
    light.master_bedroom_ceiling_fan_light:
      state: on
    light.master_bedroom_her_side:
      state: on
    light.master_bedroom_his_side:
      state: on
#   Master Entertain
- name: Master Entertain
  entities:
    light.master_bedroom_entry:
      state: on
      brightness: 102
    light.master_bedroom_ceiling_fan_light:
      state: on
      brightness: 76
    light.master_bedroom_her_side:
      state: off
    light.master_bedroom_his_side:
      state: off
#   Master Relax
- name: Master Relax
  entities:
    light.master_bedroom_entry:
      state: off
    light.master_bedroom_ceiling_fan_light:
      state: off
    light.master_bedroom_her_side:
      state: on
      brightness: 40
    light.master_bedroom_his_side:
      state: on
      brightness: 40
#   Master All Off
- name: Master All Off
  entities:
    light.master_bedroom_entry:
      state: off
    light.master_bedroom_ceiling_fan_light:
      state: off
    light.master_bedroom_her_side:
      state: off
    light.master_bedroom_his_side:
      state: off

###### SCRIPT ------------------------------------------
script:

  master_light_scene_bright:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.master_light_scene
          option: bright
      - service: scene.turn_on
        target:
          entity_id: scene.master_bright
        data:
          transition: 3
  master_light_scene_entertain:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.master_light_scene
          option: entertain
      - service: scene.turn_on
        target:
          entity_id: scene.master_entertain
        data:
          transition: 3
  master_light_scene_relax:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.master_light_scene
          option: relax
      - service: input_select.select_option
        data:
          entity_id: input_select.master_light_scene_relax_brightness
          option: level2
      - service: scene.turn_on
        target:
          entity_id: scene.master_relax
        data:
          transition: 3
  master_light_scene_off:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.master_light_scene
          option: 'off'
      - service: scene.turn_on
        target:
          entity_id: scene.master_all_off
        data:
          transition: 3


# Brightness

  master_light_scene_relax_brightness1:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.master_light_scene_relax_brightness
          option: level1
      - service: light.turn_on
        target:
          entity_id:
            - light.master_bedroom_her_side
            - light.master_bedroom_his_side
        data:
          brightness: 20
          transition: 1

  master_light_scene_relax_brightness2:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.master_light_scene_relax_brightness
          option: level2
      - service: light.turn_on
        target:
          entity_id:
            - light.master_bedroom_her_side
            - light.master_bedroom_his_side
        data:
          brightness: 40
          transition: 1

  master_light_scene_relax_brightness3:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.master_light_scene_relax_brightness
          option: level3
      - service: light.turn_on
        target:
          entity_id:
            - light.master_bedroom_her_side
            - light.master_bedroom_his_side
        data:
          brightness: 60
          transition: 1

  master_light_scene_relax_brightness4:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.master_light_scene_relax_brightness
          option: level4
      - service: light.turn_on
        target:
          entity_id:
            - light.master_bedroom_her_side
            - light.master_bedroom_his_side
        data:
          brightness: 80
          transition: 1
