
###### AUTOMATIONS --------------------------------------
automation:

- alias: Theater Off
  trigger:
  - entity_id: light.theater_ceiling
    platform: state
    to: "off"
  condition: []
  action:
  - service: light.turn_off
    target:
      entity_id: light.lifx4
    data:
      transition: 2
