
###### INPUT SELECT ------------------------------------------
input_select:

  theater_light_scene:
    name: 'Theater Light Scene'
    options:
      - bright
      - entertain
      - relax
      - 'off'

  theater_light_scene_relax:
    name: 'Theater Light Scene Relax'
    options:
      - reds
      - greens
      - blues
      - whites

  theater_light_scene_relax_brightness:
    name: 'Theater Light Scene Relax Brightness'
    options:
      - level1
      - level2
      - level3
      - level4

###### AUTOMATIONS --------------------------------------
automation:

- alias: Pico Keypad Theater Button 1
  trigger:
  - entity_id: sensor.theater_keypad
    platform: state
    to: "1"
  condition: []
  action:
  - service: script.theater_light_scene_bright

- alias: Pico Keypad Theater Button 2
  trigger:
  - entity_id: sensor.theater_keypad
    platform: state
    to: "2"
  condition: []
  action:
  - service: script.theater_light_scene_entertain

- alias: Pico Keypad Theater Button 3
  trigger:
  - entity_id: sensor.theater_keypad
    platform: state
    to: "4"
  condition: []
  action:
  - service: script.theater_light_scene_relax

- alias: Pico Keypad Theater Button 4
  trigger:
  - entity_id: sensor.theater_keypad
    platform: state
    to: "8"
  condition: []
  action:
  - service: script.theater_light_scene_off

- alias: Theater Lights Off
  trigger:
  - entity_id: group.lights_theater
    platform: state
    to: "off"
  condition: []
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.theater_light_scene
      option: 'off'

- alias: Theater Off No Keypad
  trigger:
  - entity_id: light.theater_ceiling
    platform: state
    to: "off"
  condition: []
  action:
  - service: light.turn_off
    target:
      entity_id: light.lifx4
    data:
      transition: 2

###### SCENES --------------------------------------
scene:
#   Theater Bright
- name: Theater Bright
  entities:
    light.theater_ceiling:
      state: on
      brightness: 255
    light.lifx4:
      state: on
      brightness: 255
      color_temp: 206
#   Theater Entertain
- name: Theater Entertain
  entities:
    light.theater_ceiling:
      state: on
      brightness: 155
    light.lifx4:
      state: off
#   Theater All Off
- name: Theater All Off
  entities:
    light.theater_ceiling:
      state: off
    light.lifx4:
      state: off

####   Theater Relax Colors
- name: Theater Relax Reds
  entities:
    light.theater_ceiling:
      state: off
    light.lifx4:
      state: on
      brightness: 1
      rgb_color: [255,0,50]
- name: Theater Relax Blues
  entities:
    light.theater_ceiling:
      state: off
    light.lifx4:
      state: on
      brightness: 1
      rgb_color: [28,213,255]
- name: Theater Relax Greens
  entities:
    light.theater_ceiling:
      state: off
    light.lifx4:
      state: on
      brightness: 1
      rgb_color: [32,255,21]
- name: Theater Relax Whites
  entities:
    light.theater_ceiling:
      state: off
    light.lifx4:
      state: on
      brightness: 1
      color_temp: 666

###### SCRIPT ------------------------------------------
script:

  theater_light_scene_bright:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.theater_light_scene
          option: bright
      - service: scene.turn_on
        target:
          entity_id: scene.theater_bright
        data:
          transition: 3

  theater_light_scene_entertain:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.theater_light_scene
          option: entertain
      - service: scene.turn_on
        target:
          entity_id: scene.theater_entertain
        data:
          transition: 3

  theater_light_scene_off:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.theater_light_scene
          option: 'off'
      - service: scene.turn_on
        target:
          entity_id: scene.theater_all_off
        data:
          transition: 3


### Relax Scene Options
  theater_light_scene_relax:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.theater_light_scene
          option: relax
      - service: script.turn_on
        data_template:
          entity_id: >
            {% if is_state("input_select.theater_light_scene_relax", "reds") %}
              script.theater_light_scene_relax_reds
            {% elif is_state("input_select.theater_light_scene_relax", "greens") %}
              script.theater_light_scene_relax_greens
            {% elif is_state("input_select.theater_light_scene_relax", "blues") %}
              script.theater_light_scene_relax_blues
            {% else %}
              script.theater_light_scene_relax_whites
            {% endif %}

  theater_light_scene_relax_reds:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.theater_light_scene_relax
          option: reds
      - service: input_select.select_option
        data:
          entity_id: input_select.theater_light_scene_relax_brightness
          option: level1
      - service: scene.turn_on
        target:
          entity_id: scene.theater_relax_reds
        data:
          transition: 3

  theater_light_scene_relax_blues:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.theater_light_scene_relax
          option: blues
      - service: input_select.select_option
        data:
          entity_id: input_select.theater_light_scene_relax_brightness
          option: level1
      - service: scene.turn_on
        target:
          entity_id: scene.theater_relax_blues
        data:
          transition: 3

  theater_light_scene_relax_greens:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.theater_light_scene_relax
          option: greens
      - service: input_select.select_option
        data:
          entity_id: input_select.theater_light_scene_relax_brightness
          option: level1
      - service: scene.turn_on
        target:
          entity_id: scene.theater_relax_greens
        data:
          transition: 3

  theater_light_scene_relax_whites:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.theater_light_scene_relax
          option: whites
      - service: input_select.select_option
        data:
          entity_id: input_select.theater_light_scene_relax_brightness
          option: level1
      - service: scene.turn_on
        target:
          entity_id: scene.theater_relax_whites
        data:
          transition: 3

# Brightness

  theater_light_scene_relax_brightness1:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.theater_light_scene_relax_brightness
          option: level1
      - service: light.turn_on
        target:
          entity_id:
            - light.lifx4
        data:
          brightness: 1
          transition: 1

  theater_light_scene_relax_brightness2:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.theater_light_scene_relax_brightness
          option: level2
      - service: light.turn_on
        target:
          entity_id:
            - light.lifx4
        data:
          brightness: 20
          transition: 1

  theater_light_scene_relax_brightness3:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.theater_light_scene_relax_brightness
          option: level3
      - service: light.turn_on
        target:
          entity_id:
            - light.lifx4
        data:
          brightness: 60
          transition: 1

  theater_light_scene_relax_brightness4:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.theater_light_scene_relax_brightness
          option: level4
      - service: light.turn_on
        target:
          entity_id:
            - light.lifx4
        data:
          brightness: 80
          transition: 1
