
##  Rockets
- platform: next_rocket_launch
  rocket_name:
    - "Atlas"
    - "Delta"
    - "Falcon"
    - "Soyuz"
    - "Vega"

## Templates

- platform: template
  sensors:

# Atlas
    next_rocket_atlas_comment:
      friendly_name: Next Launch
      value_template: "{{ state_attr('sensor.next_rocket_atlas', 'Comment') }}"
    next_rocket_atlas_location:
      friendly_name: Location
      value_template: "{{ state_attr('sensor.next_rocket_atlas', 'Location') }}"
    next_rocket_atlas_date:
      friendly_name: Date
      value_template: "{{ states.sensor.next_rocket_atlas.state.split('T')[0] }}"
#    next_rocket_atlas_time_full:
#      friendly_name: Time
#      value_template: "{{ states.sensor.next_rocket_atlas.state.split('T')[1] }}"
#    next_rocket_atlas_time_time:
#      friendly_name: Time
#      value_template: "{{ states.sensor.next_rocket_atlas_time_full.state.split('+')[0] }}"
#    next_rocket_atlas_time_zone:
#      friendly_name: Time
#      value_template: "{{ states.sensor.next_rocket_atlas_time_full.state.split('+')[1] }}"

# Delta
    next_rocket_delta_comment:
      friendly_name: Next Launch
      value_template: "{{ state_attr('sensor.next_rocket_delta', 'Comment') }}"
    next_rocket_delta_location:
      friendly_name: Location
      value_template: "{{ state_attr('sensor.next_rocket_delta', 'Location') }}"
    next_rocket_delta_date:
      friendly_name: Date
      value_template: "{{ states.sensor.next_rocket_delta.state.split('T')[0] }}"
#    next_rocket_delta_time_full:
#      friendly_name: Time
#      value_template: "{{ states.sensor.next_rocket_delta.state.split('T')[1] }}"
#    next_rocket_delta_time_time:
#      friendly_name: Time
#      value_template: "{{ states.sensor.next_rocket_delta_time_full.state.split('+')[0] }}"
#    next_rocket_delta_time_zone:
#      friendly_name: Time
#      value_template: "{{ states.sensor.next_rocket_delta_time_full.state.split('+')[1] }}"

# Falcon
    next_rocket_falcon_comment:
      friendly_name: Next Launch
      value_template: "{{ state_attr('sensor.next_rocket_falcon', 'Comment') }}"
    next_rocket_falcon_location:
      friendly_name: Location
      value_template: "{{ state_attr('sensor.next_rocket_falcon', 'Location') }}"
    next_rocket_falcon_date:
      friendly_name: Date
      value_template: "{{ states.sensor.next_rocket_falcon.state.split('T')[0] }}"
#    next_rocket_falcon_time_full:
#      friendly_name: Time
#      value_template: "{{ states.sensor.next_rocket_falcon.state.split('T')[1] }}"
#    next_rocket_falcon_time_time:
#      friendly_name: Time
#      value_template: "{{ states.sensor.next_rocket_falcon_time_full.state.split('+')[0] }}"
#    next_rocket_falcon_time_zone:
#      friendly_name: Time
#      value_template: "{{ states.sensor.next_rocket_falcon_time_full.state.split('+')[1] }}"

# Soyuz
    next_rocket_soyuz_comment:
      friendly_name: Next Launch
      value_template: "{{ state_attr('sensor.next_rocket_soyuz', 'Comment') }}"
    next_rocket_soyuz_location:
      friendly_name: Location
      value_template: "{{ state_attr('sensor.next_rocket_soyuz', 'Location') }}"
    next_rocket_soyuz_date:
      friendly_name: Date
      value_template: "{{ states.sensor.next_rocket_soyuz.state.split('T')[0] }}"
#    next_rocket_soyuz_time_full:
#      friendly_name: Time
#      value_template: "{{ states.sensor.next_rocket_soyuz.state.split('T')[1] }}"
#    next_rocket_soyuz_time_time:
#      friendly_name: Time
#      value_template: "{{ states.sensor.next_rocket_soyuz_time_full.state.split('+')[0] }}"
#    next_rocket_soyuz_time_zone:
#      friendly_name: Time
#      value_template: "{{ states.sensor.next_rocket_soyuz_time_full.state.split('+')[1] }}"

# Vega
    next_rocket_vega_comment:
      friendly_name: Next Launch
      value_template: "{{ state_attr('sensor.next_rocket_vega', 'Comment') }}"
    next_rocket_vega_location:
      friendly_name: Location
      value_template: "{{ state_attr('sensor.next_rocket_vega', 'Location') }}"
    next_rocket_vega_date:
      friendly_name: Date
      value_template: "{{ states.sensor.next_rocket_vega.state.split('T')[0] }}"
#    next_rocket_vega_time_full:
#      friendly_name: Time
#      value_template: "{{ states.sensor.next_rocket_vega.state.split('T')[1] }}"
#    next_rocket_vega_time_time:
#      friendly_name: Time
#      value_template: "{{ states.sensor.next_rocket_vega_time_full.state.split('+')[0] }}"
#    next_rocket_vega_time_zone:
#      friendly_name: Time
#      value_template: "{{ states.sensor.next_rocket_vega_time_full.state.split('+')[1] }}"


