
### Templates

- platform: template
  sensors:
    front_gate_status:
      friendly_name: "Front Gate Status"
      value_template: >-
        {% if is_state('switch.gate_relay_1', 'off') %}
          Locked
        {% else %}
          Unlocked
        {% endif %}

    front_door_battery:
      value_template: "{{ state_attr('zwave.schlage_allegion_be469_touchscreen_deadbolt', 'battery_level') }}%"

    sony_receiver_muting:
      friendly_name: Sony Receiver Muting
      value_template: "{{ state_attr('media_player.sony_receiver', 'is_volume_muted') }}"

    living_fan_speed:
      friendly_name: Living Room Fan Speed
      value_template: "{{ state_attr('fan.living_room_ceiling_fan', 'speed') }}"

    ps4_source:
      friendly_name: PS4 Current Game
      value_template: "{{ state_attr('media_player.playstation_4', 'source') }}"

    ps4_unavailable:
      friendly_name: "PlayStation Unavailable"
      value_template: >-
        {% if is_state('media_player.playstation_4', 'unavailable') %}
          true
        {% else %}
          false
        {% endif %}

    living_room_tv_cast_unavailable:
      friendly_name: "Living Room TV Cast Unavailable"
      value_template: >-
        {% if is_state('media_player.living_room_tv', 'unavailable') %}
          true
        {% else %}
          false
        {% endif %}

    vesync_white_watts:
      friendly_name: VeSync White Watts
      value_template: "{{ state_attr('switch.vesync_white', 'current_power_w') }}"
      unit_of_measurement: 'W'

    vesync_blue_watts:
      friendly_name: VeSync Blue Watts
      value_template: "{{ state_attr('switch.vesync_blue', 'current_power_w') }}"
      unit_of_measurement: 'W'

    vesync_rack_watts:
      friendly_name: VeSync Rack Watts
      value_template: "{{ (state_attr('switch.rack_power', 'current_power_w')) | round(2) }}"
      unit_of_measurement: 'W'

    vesync_projector_watts:
      friendly_name: VeSync Projector Watts
      value_template: "{{ (state_attr('switch.projector_power', 'current_power_w')) | round(2) }}"
      unit_of_measurement: 'W'

    vesync_theater_watts:
      friendly_name: VeSync Theater Watts
      value_template: "{{ (state_attr('switch.rack_power', 'current_power_w')+state_attr('switch.projector_power', 'current_power_w')) | round(2) }}"
      unit_of_measurement: 'W'

#    vesync_white_voltage:
#      friendly_name: VeSync White Voltage
#      value_template: "{{ state_attr('switch.vesync_white', 'voltage') }} V"

#    vesync_blue_voltage:
#      friendly_name: VeSync Blue Voltage
#      value_template: "{{ state_attr('switch.vesync_blue', 'voltage') }} V"

#    vesync_white_current:
#      friendly_name: VeSync White Current 
#      value_template: "{{ state_attr('switch.vesync_white', 'current_power_w') / state_attr('switch.vesync_white', 'voltage') }} A"

#    vesync_blue_current:
#      friendly_name: VeSync Blue Current
#      value_template: "{{ state_attr('switch.vesync_blue', 'current_power_w') / state_attr('switch.vesync_blue', 'voltage') }} A"

