
### Templates

- platform: template
  sensors:

    bed3_fan_speed:
      friendly_name: Bed3 Fan Speed
      value_template: "{{ state_attr('fan.bed3_ceiling_fan', 'speed') }}"

    living_fan_speed:
      friendly_name: Living Room Fan Speed
      value_template: "{{ state_attr('fan.living_room_ceiling_fan', 'speed') }}"

    master_bedroom_fan_speed:
      friendly_name: Master Bedroom Fan Speed
      value_template: "{{ state_attr('fan.master_bedroom_ceiling_fan', 'speed') }}"
