## Master TV

# Chromecast
- alias: Master Bed Cast Started
  trigger:
  - platform: state
    entity_id: media_player.bedroom_tv
    from: "off"
  condition: []
  action:
  - service: media_player.volume_set
    data:
      entity_id: media_player.bedroom_tv
      volume_level: 0.7

- alias: Master Bed Cast Ended
  trigger:
  - platform: state
    entity_id: media_player.bedroom_tv
    to: "off"
  condition: []
  action:
  - service: script.turn_on
    entity_id: script.master_tv_power_off
