##  Lighting

#   Garage Opening Lights On
- alias: Garage Opening Lights On
  trigger:
  - entity_id: sensor.garage_door_contact
    platform: state
    to: Open
  condition:
  - condition: state
    entity_id: sun.sun
    state: 'below_horizon'
  action:
  - service: scene.turn_on
    data:
      entity_id: scene.exterior_garage_driveway_on

#   Garage Closed Lights Off
- alias: Garage Closed Lights Off
  trigger:
  - entity_id: sensor.garage_door_contact
    platform: state
    to: Closed
    for: "00:00:30"
  action:
  - service: scene.turn_on
    data:
      entity_id: scene.exterior_garage_driveway_off
