##  Lighting

#   Exterior Lighting
- alias: Exterior Lights Off Sunrise
  trigger:
  - platform: sun
    event: sunrise
  condition: []
  action:
  - service: light.turn_off
    data:
      entity_id: light.exterior_front_door
      transition: 10
  - service: light.turn_off
    data:
      entity_id: light.exterior_back_door
      transition: 10
  - service: light.turn_off
    data:
      entity_id: light.exterior_driveway
      transition: 10

- alias: Exterior Lights On Sunset
  trigger:
  - platform: sun
    event: sunset
  condition: []
  action:
  - service: light.turn_on
    data:
      entity_id: light.exterior_front_door
      brightness: 125
      transition: 2
  - service: light.turn_on
    data:
      entity_id: light.exterior_back_door
      brightness: 125
      transition: 2
  - service: light.turn_on
    data:
      entity_id: light.exterior_driveway
      brightness: 80
      transition: 2
