##  Lighting

#   Kitchen Lights On with Switch
#- alias: Auto Dim Kitchen Ceiling
#  trigger:
#  - entity_id: light.kitchen_ceiling
#    platform: state
#    to: "on"
#  condition:
#  - condition: template
#    value_template: "{{ state_attr('light.kitchen_ceiling', 'brightness') > 250 }}"
#  action:
#  - service: light.turn_on
#    data:
#      entity_id: light.kitchen_ceiling
#      brightness: 143

#- alias: Auto Dim Kitchen Sink
#  trigger:
#  - entity_id: light.kitchen_sink
#    platform: state
#  condition:
#  - condition: template
#    value_template: "{{ state_attr('light.kitchen_sink', 'brightness') > 250 }}"
#  action:
#  - service: light.turn_on
#    data:
#      entity_id: light.kitchen_sink
#      brightness: 64

- alias: Auto Dim Kitchen Dining
  trigger:
  - entity_id: light.kitchen_dining_pendant
    platform: state
    to: "on"
  condition:
  - condition: template
    value_template: "{{ state_attr('light.kitchen_dining_pendant', 'brightness') > 250 }}"
  action:
  - service: light.turn_on
    data:
      entity_id: light.kitchen_dining_pendant
      brightness: 126

#   Living Room Lights On
- alias: Auto Dim Living Ceiling
  trigger:
  - entity_id: light.living_room_main
    platform: state
    to: "on"
  condition:
  - condition: template
    value_template: "{{ state_attr('light.living_room_main', 'brightness') > 250 }}"
  action:
  - service: light.turn_on
    data:
      entity_id: light.living_room_main
      brightness: 120

#   Master Bedroom Lights On
#- alias: Auto Dim Master Ceiling
#  trigger:
#  - entity_id: light.master_bedroom_ceiling_fan_light
#    platform: state
#    to: "on"
#  condition:
#  - condition: template
#    value_template: "{{ state_attr('light.master_bedroom_ceiling_fan_light', 'brightness') > 250 }}"
#  action:
#  - service: light.turn_on
#    data:
#      entity_id: light.master_bedroom_ceiling_fan_light
#      brightness: 64

#- alias: Auto Dim Master Entry
#  trigger:
#  - entity_id: light.master_bedroom_entry
#    platform: state
#    to: "on"
#  condition:
#  - condition: template
#    value_template: "{{ state_attr('light.master_bedroom_entry', 'brightness') > 250 }}"
#  action:
#  - service: light.turn_on
#    data:
#      entity_id: light.master_bedroom_entry
#      brightness: 64
