### Lighting

# Nobody Home Sunset - Phonebooth On
- alias: Phonebooth Off Sunrise
  trigger:
    platform: sun
    event: sunrise
  action:
  - service: switch.turn_off
    data:
      entity_id: switch.plug_in_switch_switch

- alias: Phonebooth On Nobody Home Sunset
  trigger:
    platform: sun
    event: sunset
  condition:
  - condition: state
    entity_id: person.ian
    state: 'not_home'
  - condition: state
    entity_id: person.sean
    state: 'not_home'
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.plug_in_switch_switch

- alias: Phonebooth On Nobody Home Sunset 1
  trigger:
    platform: sun
    event: sunset
    offset: "+01:00:00"
  condition:
  - condition: state
    entity_id: person.ian
    state: 'not_home'
  - condition: state
    entity_id: person.sean
    state: 'not_home'
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.plug_in_switch_switch

- alias: Phonebooth On Nobody Home Sunset 2
  trigger:
    platform: sun
    event: sunset
    offset: "+02:00:00"
  condition:
  - condition: state
    entity_id: person.ian
    state: 'not_home'
  - condition: state
    entity_id: person.sean
    state: 'not_home'
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.plug_in_switch_switch

- alias: Phonebooth On Nobody Home Sunset 3
  trigger:
    platform: sun
    event: sunset
    offset: "+03:00:00"
  condition:
  - condition: state
    entity_id: person.ian
    state: 'not_home'
  - condition: state
    entity_id: person.sean
    state: 'not_home'
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.plug_in_switch_switch

- alias: Phonebooth On Nobody Home Sunset 4
  trigger:
    platform: sun
    event: sunset
    offset: "+04:00:00"
  condition:
  - condition: state
    entity_id: person.ian
    state: 'not_home'
  - condition: state
    entity_id: person.sean
    state: 'not_home'
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.plug_in_switch_switch

- alias: Phonebooth On Nobody Home Sunset 5
  trigger:
    platform: sun
    event: sunset
    offset: "+05:00:00"
  condition:
  - condition: state
    entity_id: person.ian
    state: 'not_home'
  - condition: state
    entity_id: person.sean
    state: 'not_home'
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.plug_in_switch_switch
