
# Nobody Home - Front Unlocked for 10 Minutes
- alias: Front Door Unlocked Vacant 10
  trigger:
  - entity_id: lock.front_door
    platform: state
    to: unlocked
    for: "00:10:00"
  condition:
  - condition: state
    entity_id: group.all_persons
    state: 'not_home'
  action:
  - service: camera.snapshot
    data:
      entity_id: camera.frontdoor
      filename: '/config/www/front_door.jpg'
  - service: !secret notify_ian
    data:
      title: Front Door Unlocked for 10 Minutes
      message: Nobody is Home
      data:
        push:
          category: front_door_unlocked
        attachment:
          url: !secret snapshot_frontdoor
  - service: !secret notify_sean
    data:
      title: Front Door Unlocked for 10 Minutes
      message: Nobody is Home
      data:
        push:
          category: front_door_unlocked
        attachment:
          url: !secret snapshot_frontdoor

# Nobody Home - Front Unlocked for 20 Minutes
- alias: Front Door Unlocked Vacant 20
  trigger:
  - entity_id: lock.front_door
    platform: state
    to: unlocked
    for: "00:20:00"
  condition:
  - condition: state
    entity_id: group.all_persons
    state: 'not_home'
  action:
  - service: camera.snapshot
    data:
      entity_id: camera.frontdoor
      filename: '/config/www/front_door.jpg'
  - service: !secret notify_ian
    data:
      title: Front Door Unlocked for 20 Minutes
      message: Nobody is Home
      data:
        push:
          category: front_door_unlocked
        attachment:
          url: !secret snapshot_frontdoor
  - service: !secret notify_sean
    data:
      title: Front Door Unlocked for 20 Minutes
      message: Nobody is Home
      data:
        push:
          category: front_door_unlocked
        attachment:
          url: !secret snapshot_frontdoor

# Nobody Home - Front Unlocked for 30 Minutes
- alias: Front Door Unlocked Vacant 30
  trigger:
  - entity_id: lock.front_door
    platform: state
    to: unlocked
    for: "00:30:00"
  condition:
  - condition: state
    entity_id: group.all_persons
    state: 'not_home'
  action:
  - service: camera.snapshot
    data:
      entity_id: camera.frontdoor
      filename: '/config/www/front_door.jpg'
  - service: !secret notify_ian
    data:
      title: Front Door Unlocked for 30 Minutes
      message: Nobody is Home
      data:
        push:
          category: front_door_unlocked
        attachment:
          url: !secret snapshot_frontdoor
  - service: !secret notify_sean
    data:
      title: Front Door Unlocked for 30 Minutes
      message: Nobody is Home
      data:
        push:
          category: front_door_unlocked
        attachment:
          url: !secret snapshot_frontdoor
