### Notification Actions

# Close Garage
- alias: Notify Action Garage Close
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: CLOSE_GARAGE
  action:
  - service: cover.close_cover
    data:
      entity_id: cover.garage_door

# Open Garage
- alias: Notify Action Garage Open
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: OPEN_GARAGE
  action:
  - service: cover.open_cover
    data:
      entity_id: cover.garage_door

# Disable Garage Notifications
- alias: Notify Action Garage Disable Notifications
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: STOP_NOTIFY
  action:
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.notify_garage

# Lock Front Door
- alias: Notify Action Front Door Lock
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: LOCK_FRONT_DOOR
  action:
  - service: lock.lock
    data:
      entity_id: lock.front_door

# Unlock Front Door
- alias: Notify Action Front Door Unlock
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: UNLOCK_FRONT_DOOR
  action:
  - service: lock.unlock
    data:
      entity_id: lock.front_door

# Get Report
#- alias: Notify Action Get Report
#  trigger:
#    platform: event
#    event_type: ios.notification_action_fired
#    event_data:
#      actionName: GET_REPORT
#  action:
#  - service: !secret notify_ian
#    data:
#      message: Garage Door is {{ states.cover.garage_door.state }}
