
# Nobody Home - Front Unlocked for 10 Minutes
- alias: Front Door Unlocked Vacant 10
  trigger:
  - entity_id: group.all_persons
    platform: state
    to: not_home
    for: "00:10:00"
  condition:
  - condition: state
    entity_id: lock.front_door
    state: 'unlocked'
  action:
  - service: camera.snapshot
    data:
      entity_id: camera.frontdoor
      filename: '/config/www/front_door.jpg'
  - service: !secret notify_ian
    data:
      title: Front Door Unlocked
      message: Nobody has been home for 10 minutes
      data:
        push:
          category: front_door_unlocked
        attachment:
          url: !secret snapshot_frontdoor
  - service: !secret notify_sean
    data:
      title: Front Door Unlocked
      message: Nobody has been home for 10 minutes
      data:
        push:
          category: front_door_unlocked
        attachment:
          url: !secret snapshot_frontdoor

# Nobody Home - Front Unlocked for 30 Minutes
- alias: Front Door Unlocked Vacant 30
  trigger:
  - entity_id: group.all_persons
    platform: state
    to: not_home
    for: "00:30:00"
  condition:
  - condition: state
    entity_id: lock.front_door
    state: 'unlocked'
  action:
  - service: lock.lock
    data:
      entity_id: lock.front_door
  - service: camera.snapshot
    data:
      entity_id: camera.frontdoor
      filename: '/config/www/front_door.jpg'
  - service: !secret notify_ian
    data:
      title: Front Door Automatically Locked
      message: Nobody has been home for 30 minutes
      data:
        push:
          category: front_door_unlocked
        attachment:
          url: !secret snapshot_frontdoor
  - service: !secret notify_sean
    data:
      title: Front Door Automatically Locked
      message: Nobody has been home for 30 minutes
      data:
        push:
          category: front_door_unlocked
        attachment:
          url: !secret snapshot_frontdoor
