
##  Pico Takeover Garage

#- alias: Pico Garage Button 1
#  trigger:
#  - entity_id: sensor.garage_pico
#    platform: state
#    to: "1"
#  condition: []
#  action:
#  - service:
#    data:

- alias: Pico Garage Button 2
  trigger:
  - entity_id: sensor.garage_pico
    platform: state
    to: "8"
  condition: []
  action:
  - service: cover.open_cover
    data:
      entity_id: cover.garage_door
  - service: switch.turn_on
    data:
      entity_id: switch.garage_ceiling

- alias: Pico Garage Button 3
  trigger:
  - entity_id: sensor.garage_pico
    platform: state
    to: "2"
  condition: []
  action:
  - service: scene.turn_on
    data:
      entity_id: scene.kitchen_all_off
  - service: scene.turn_on
    data:
      entity_id: scene.living_all_off

- alias: Pico Garage Button 3 Hold
  trigger:
  - entity_id: sensor.garage_pico
    platform: state
    to: "2"
    for: "00:00:02"
  condition: []
  action:
  - service: homeassistant.turn_off
    data:
      entity_id: group.lights_downstairs

- alias: Pico Garage Button 4
  trigger:
  - entity_id: sensor.garage_pico
    platform: state
    to: "16"
  condition: []
  action:
  - service: cover.close_cover
    data:
      entity_id: cover.garage_door

#- alias: Pico Garage Button 5
#  trigger:
#  - entity_id: sensor.garage_pico
#    platform: state
#    to: "4"
#  condition: []
#  action:
#  - service:
#    data:
