
##  Pico Takeover Kitchen

#- alias: Pico Kitchen Button 1
#  trigger:
#  - entity_id: sensor.kitchen_pico
#    platform: state
#    to: "1"
#  condition: []
#  action:
#  - service: light.turn_on
#    data:
#      entity_id: light.kitchen_dining_pendant
#      brightness: 126

#- alias: Pico Kitchen Button 2
#  trigger:
#  - entity_id: sensor.kitchen_pico
#    platform: state
#    to: "8"
#  condition: []
#  action:
#  - service: light.turn_on
#    data:
#      entity_id: light.kitchen_dining_pendant
#      brightness: 126

- alias: Pico Kitchen Button 3
  trigger:
  - entity_id: sensor.kitchen_pico
    platform: state
    to: "2"
  condition: []
  action:
  - service: scene.create
    data:
      scene_id: pico_favorite_ignore_kitchen
      snapshot_entities:
      - light.kitchen_ceiling
      - light.kitchen_sink
  - service: switch.toggle
    data:
      entity_id: switch.kitchen_cabinets
  - service: scene.turn_on
    data:
      entity_id: scene.pico_favorite_ignore_kitchen

#- alias: Pico Kitchen Button 4
#  trigger:
#  - entity_id: sensor.kitchen_pico
#    platform: state
#    to: "16"
#  condition: []
#  action:
#  - service: light.turn_off
#    data:
#      entity_id: light.kitchen_dining_pendant

- alias: Pico Kitchen Button 5
  trigger:
  - entity_id: sensor.kitchen_pico
    platform: state
    to: "4"
  condition: []
  action:
  - service: switch.turn_off
    data:
      entity_id: switch.kitchen_cabinets


