
##  Pico Takeover Template

#- alias: Pico Front Door Button 1
#  trigger:
#  - entity_id: sensor.front_door_pico
#    platform: state
#    to: "1"
#  condition: []
#  action:
#  - service: 
#    data:
#      entity_id: 

#- alias: Pico Front Door Button 2
#  trigger:
#  - entity_id: sensor.front_door_pico
#    platform: state
#    to: "8"
#  condition: []
#  action:
#  - service: 
#    data:
#      entity_id: 

- alias: Pico Front Door Button 3
  trigger:
  - entity_id: sensor.front_door_pico
    platform: state
    to: "2"
  condition: []
  action:
  - service: scene.create
    data:
      scene_id: pico_favorite_ignore_frontdoor
      snapshot_entities:
      -  light.exterior_front_door
  - service: switch.toggle
    data:
      entity_id: switch.patio_string
  - service: scene.turn_on
    data:
      entity_id: scene.pico_favorite_ignore_frontdoor
#- alias: Pico Front Door Button 4
#  trigger:
#  - entity_id: sensor.front_door_pico
#    platform: state
#    to: "16"
#  condition: []
#  action:
#  - service: 
#    data:
#      entity_id: 

- alias: Pico Front Door Button 5
  trigger:
  - entity_id: sensor.front_door_pico
    platform: state
    to: "4"
  condition: []
  action:
  - service: switch.turn_off
    data:
      entity_id: switch.patio_string


