#   Sprinklers Off Automatically
- alias: Sprinklers Auto Off
  trigger:
  - platform: state
    entity_id: switch.sprinklers
    to: "on"
    for: "00:00:10"
  condition: []
  action:
  - service: switch.turn_off
    data:
      entity_id: switch.sprinklers
