
###### SENSOR TEMPLATES ------------------------------------------


###### INPUT BOOLEANS ------------------------------------------


###### GROUPS ----------------------------------------

group:
 persons_we:
  name: Persons We
  entities:
  - person.ian
  - person.kalene

###### AUTOMATIONS --------------------------------------
automation:
- alias: Not Home - All
  trigger:
  - platform: state
    entity_id: group.all_persons
    to: not_home
    for: "00:05:00"
  action:
  - service: light.turn_off
    data:
      entity_id: group.lights_all
  - service: script.turn_on
    data:
      entity_id: script.fan_living_low

- alias: Not Home - We
  trigger:
  - platform: state
    entity_id: group.persons_we
    to: not_home
#    for: "00:05:00"
  action:
  - service: light.turn_off
    data:
      entity_id: group.lights_master
  - service: script.turn_on
    data:
      entity_id: script.fan_master_low

- alias: Not Home - Nathan
  trigger:
  - platform: state
    entity_id: person.nathan
    to: not_home
#    for: "00:05:00"
  action:
  - service: light.turn_off
    data:
      entity_id: group.lights_bed3
  - service: script.turn_on
    data:
      entity_id: script.fan_bed3_low
  - service: script.turn_on
    data:
      entity_id: script.bed3_shade_blackout_close
  - service: script.turn_on
    data:
      entity_id: script.bed3_shade_screen_close

###### SCRIPTS ------------------------------------------
