# RESOURCES:
 # Credit to /u/dsgraham on Reddit - https://www.reddit.com/r/homeassistant/comments/9n0llr/google_ambient_sound_urls/
 # Script adapted from Bob_NL on Home Assistant Forums - https://community.home-assistant.io/t/chromecast-radio-with-station-and-player-selection/12732
# Google webpage: https://support.google.com/googlehome/answer/7364558?hl=en

###### CUSTOMIZE ----------------------------------------

homeassistant:
  customize:
    script.play_spotify:
      icon: mdi:play
      friendly_name: Start Playing

###### INPUT SELECT ------------------------------------------
  
input_select:
  spotify_playlist:
    name: 'Select Playlist:'
    options:
      - Peaceful Piano
      - Lo-Fi Beats
      - On Repeat
      - Repeat Rewind
      - Rock Classics
      - 2000's
      - 1990's
      - Alternative
      - Discover Weekly
    initial: Rock Classics
  cast_speaker:
    name: 'Select Speakers:'
    options:
      - Everywhere
      - Woofer Zones
      - Master Suite
      - Living Room TV
      - Theater TV
    initial: Everywhere
    icon: mdi:speaker-wireless

###### INPUT NUMBER -------------------------------------

input_number: 
  volume_play_spotify:
    name: Volume
    icon: mdi:volume-high
    min: 0
    max: 1
    step: 0.05 

###### SCRIPTS ------------------------------------------


###### AUTOMATIONS --------------------------------------

automation:
- alias: Ambient Sounds Toggle
  trigger:
    platform: state
    entity_id: input_boolean.ambient_sounds
    to: 'on'
  condition: []
  action:
    service: input_boolean.turn_off
    data:
      entity_id: input_boolean.ambient_spotify
- alias: Ambient Spotify Toggle
  trigger:
    platform: state
    entity_id: input_boolean.ambient_spotify
    to: 'on'
  condition: []
  action:
    service: input_boolean.turn_off
    data:
      entity_id: input_boolean.ambient_sounds
