# RESOURCES:
 # Credit to /u/dsgraham on Reddit - https://www.reddit.com/r/homeassistant/comments/9n0llr/google_ambient_sound_urls/
 # Script adapted from Bob_NL on Home Assistant Forums - https://community.home-assistant.io/t/chromecast-radio-with-station-and-player-selection/12732
# Google webpage: https://support.google.com/googlehome/answer/7364558?hl=en

###### CUSTOMIZE ----------------------------------------

homeassistant:
  customize:
    script.ambientsounds:
      icon: mdi:play
      friendly_name: Start Playing

###### GROUPS ----------------------------------------

group:
 Ambient Sounds:
  name: Ambient Sounds
  entities:
  - input_select.ambient_sound
  - input_select.ambient_speaker
  - script.ambientsounds
  - input_number.volume_ambientsounds

###### INPUT SELECT ------------------------------------------
input_select:
  ambient_sound:
    name: 'Select Radio Station:'
    options:
      - None
      - Babbling Brook
      - Oscillating Fan
      - Fireplace
      - Forest
      - Country Night
      - Ocean
      - Rain
      - River
      - Thunderstorm
      - White Noise
  ambient_speaker:
    name: 'Select Speakers:'
    options:
      - Everywhere
      - Woofer Zones
      - Master Suite
      - Living Room TV
      - Theater TV
    initial: Everywhere
    icon: mdi:speaker-wireless

###### INPUT BOOLEANS ------------------------------------------
input_boolean:
  ambient_sounds:
    name: Ambient Sounds
    initial: off

###### INPUT NUMBER ------------------------------------------
input_number: 
  volume_ambientsounds:
    name: Volume
    icon: mdi:volume-high
    min: 0
    max: 1
    step: 0.05 

###### SCRIPTS ------------------------------------------
    
script:
  ambientsounds:
    alias: Play Ambient Sounds
    sequence:
      - service: media_player.play_media
        data_template:
          entity_id: >
            {% if is_state("input_select.ambient_speaker", "Everywhere") %} media_player.everywhere
            {% elif is_state("input_select.ambient_speaker", "Woofer Zones") %} media_player.woofers
            {% elif is_state("input_select.ambient_speaker", "Master Suite") %} media_player.master
            {% elif is_state("input_select.ambient_speaker", "Living Room TV") %} media_player.living_room_tv
            {% elif is_state("input_select.ambient_speaker", "Theater TV") %} media_player.theater_tv
            {% endif %}
          media_content_id: >
            {% if is_state("input_select.ambient_sound", "Babbling Brook") %} https://www.gstatic.com/voice_delight/sounds/long/brook.mp3
            {% elif is_state("input_select.ambient_sound", "Oscillating Fan") %} https://www.gstatic.com/voice_delight/sounds/long/oscillating_fan.mp3
            {% elif is_state("input_select.ambient_sound", "Fireplace") %} https://www.gstatic.com/voice_delight/sounds/long/fireplace.mp3
            {% elif is_state("input_select.ambient_sound", "Forest") %} https://www.gstatic.com/voice_delight/sounds/long/forest.mp3
            {% elif is_state("input_select.ambient_sound", "Country Night") %} https://www.gstatic.com/voice_delight/sounds/long/country_night.mp3
            {% elif is_state("input_select.ambient_sound", "Ocean") %} https://www.gstatic.com/voice_delight/sounds/long/ocean.mp3
            {% elif is_state("input_select.ambient_sound", "Rain") %} https://www.gstatic.com/voice_delight/sounds/long/rain.mp3
            {% elif is_state("input_select.ambient_sound", "River") %} https://www.gstatic.com/voice_delight/sounds/long/river.mp3
            {% elif is_state("input_select.ambient_sound", "Thunderstorm") %} https://www.gstatic.com/voice_delight/sounds/long/thunder.mp3
            {% elif is_state("input_select.ambient_sound", "White Noise") %} https://www.gstatic.com/voice_delight/sounds/long/pink_noise.mp3
            {% endif %}
          media_content_type: 'audio/mp4'
