
###### INPUT BOOLEANS ------------------------------------------

input_boolean:
  master_ledstrip_alarm:
    name: Master LED Strip Alarm
  master_bedtime_active:
    name: Master Bedtime Active

###### INPUT SELECT ------------------------------------------

input_select:
  alarm_wakeup_sounds:
    name: 'Select Sounds:'
    options:
      - None
      - Babbling Brook
      - Oscillating Fan
      - Fireplace
      - Forest
      - Country Night
      - Ocean
      - Rain
      - River
      - Thunderstorm
      - White Noise

###### SCRIPT ------------------------------------------
script:
# Bedtime Begins Trigger
  bedtime_begins_trigger:
    alias: Bedtime Begins Trigger
    sequence:
      - service: script.bedtime_begins_lights
      - service: script.turn_on
        data_template:
          entity_id: >
            {% if is_state("input_select.alarm_wakeup_sounds", "None") %}
              none
            {% else %}
              script.bedtime_begins_sounds
            {% endif %}
      - service: input_boolean.turn_on
        data_template:
          entity_id: input_boolean.master_bedtime_active

  bedtime_begins_lights:
    alias: Bedtime Begins Lights
    sequence:
      - service: script.master_ledstrip_power_on
      - delay:
          milliseconds: 200
      - service: script.master_ledstrip_red
      - delay:
          milliseconds: 200
      - service: script.master_ledstrip_power_off

  bedtime_begins_sounds:
    alias: Bedtime Begins Sounds
    sequence:
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.bedroom_speaker
          volume_level: 0.2
      - delay:
          milliseconds: 200
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.bathroom_speaker
          volume_level: 0.2

# Bedtime Manually Cancelled
  bedtime_cancelled:
    alias: Bedtime Cancelled
    sequence:
      - service: input_boolean.turn_off
        data_template:
          entity_id: input_boolean.master_bedtime_active

# Alarm Wakeup Trigger
  alarm_wakeup_trigger:
    alias: Alarm Wakeup Trigger
    sequence:
      - service: input_boolean.turn_off
        data_template:
          entity_id: input_boolean.master_bedtime_active
      - service: script.turn_on
        data_template:
          entity_id: >
            {% if is_state("input_boolean.master_ledstrip_alarm", "on") %}
              script.alarm_wakeup_lights
            {% else %}
              none
            {% endif %}
      - service: script.turn_on
        data_template:
          entity_id: >
            {% if is_state("input_select.alarm_wakeup_sounds", "None") %}
              none
            {% else %}
              script.alarm_wakeup_sounds
            {% endif %}

  alarm_wakeup_lights:
    alias: Alarm Lights
    sequence:
      - service: script.master_ledstrip_power_on
      - delay:
          milliseconds: 200
      - service: script.master_ledstrip_red_3

  alarm_wakeup_sounds:
    alias: Alarm Sounds
    sequence:
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.bedroom_speaker
          volume_level: 0.2
      - delay:
          milliseconds: 200
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.bathroom_speaker
          volume_level: 0.2
      - delay:
          milliseconds: 200
      - service: media_player.play_media
        data_template:
          entity_id: media_player.master
          media_content_id: >
            {% if is_state("input_select.alarm_wakeup_sounds", "Babbling Brook") %}
              https://www.gstatic.com/voice_delight/sounds/long/brook.mp3
            {% elif is_state("input_select.alarm_wakeup_sounds", "Oscillating Fan") %}
              https://www.gstatic.com/voice_delight/sounds/long/oscillating_fan.mp3
            {% elif is_state("input_select.alarm_wakeup_sounds", "Fireplace") %}
              https://www.gstatic.com/voice_delight/sounds/long/fireplace.mp3
            {% elif is_state("input_select.alarm_wakeup_sounds", "Forest") %}
              https://www.gstatic.com/voice_delight/sounds/long/forest.mp3
            {% elif is_state("input_select.alarm_wakeup_sounds", "Country Night") %}
              https://www.gstatic.com/voice_delight/sounds/long/country_night.mp3
            {% elif is_state("input_select.alarm_wakeup_sounds", "Ocean") %}
              https://www.gstatic.com/voice_delight/sounds/long/ocean.mp3
            {% elif is_state("input_select.alarm_wakeup_sounds", "Rain") %}
              https://www.gstatic.com/voice_delight/sounds/long/rain.mp3
            {% elif is_state("input_select.alarm_wakeup_sounds", "River") %}
              https://www.gstatic.com/voice_delight/sounds/long/river.mp3
            {% elif is_state("input_select.alarm_wakeup_sounds", "Thunderstorm") %}
              https://www.gstatic.com/voice_delight/sounds/long/thunder.mp3
            {% elif is_state("input_select.alarm_wakeup_sounds", "White Noise") %}
              https://www.gstatic.com/voice_delight/sounds/long/pink_noise.mp3
            {% else %}
              none
            {% endif %}
          media_content_type: 'audio/mp4'


###### AUTOMATIONS --------------------------------------
automation:

# LED Control
- alias: Master Motion LED On
  trigger:
  - platform: state
    entity_id: binary_sensor.wyzesense_motion_masterbed
    to: "on"
  condition:
  - condition: state
    entity_id: input_boolean.master_bedtime_active
    state: "on"
  action:
  - service: script.master_ledstrip_power_on
  - delay:
      milliseconds: 200
  - service: script.master_ledstrip_red

- alias: Master Motion LED Off
  trigger:
  - platform: state
    entity_id: binary_sensor.wyzesense_motion_masterbed
    to: "off"
  condition:
  - condition: state
    entity_id: input_boolean.master_bedtime_active
    state: "on"
  action:
  - service: script.master_ledstrip_power_off
