### Google Homes

## Preset Volumes
script:
# Soft
  volume_set_soft:
    alias: Volume Set Soft
    sequence:
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.bathroom_speaker
          volume_level: 0.15
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.bedroom_speaker
          volume_level: 0.2
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.front_patio_speaker
          volume_level: 0.2
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.guest_bathroom_speaker
          volume_level: 0.15
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.guest_room_speaker
          volume_level: 0.2
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.kitchen_speaker
          volume_level: 0.3
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.living_room_speaker
          volume_level: 0.3
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.theater_speaker
          volume_level: 0.2
# Medium
  volume_set_medium:
    alias: Volume Set Loud
    sequence:
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.bathroom_speaker
          volume_level: 0.3
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.bedroom_speaker
          volume_level: 0.4
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.front_patio_speaker
          volume_level: 0.4
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.guest_bathroom_speaker
          volume_level: 0.3
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.guest_room_speaker
          volume_level: 0.4
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.kitchen_speaker
          volume_level: 0.5
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.living_room_speaker
          volume_level: 0.5
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.theater_speaker
          volume_level: 0.4
# Loud
  volume_set_loud:
    alias: Volume Set Loud
    sequence:
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.bathroom_speaker
          volume_level: 0.6
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.bedroom_speaker
          volume_level: 0.6
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.front_patio_speaker
          volume_level: 0.7
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.guest_bathroom_speaker
          volume_level: 0.6
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.guest_room_speaker
          volume_level: 0.6
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.kitchen_speaker
          volume_level: 0.7
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.living_room_speaker
          volume_level: 0.7
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.theater_speaker
          volume_level: 0.6

## Volume Set
automation:
# 9pm
- alias: Speakers Volume Set 9pm
  trigger:
  - platform: time
    at: "21:00:30"
  action:
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.bathroom_speaker
        volume_level: 0.15
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.bedroom_speaker
        volume_level: 0.2
#    - service: media_player.volume_set
#      data_template:
#        entity_id: media_player.front_patio_speaker
#        volume_level: 0.1
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.guest_bathroom_speaker
        volume_level: 0.15
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.guest_room_speaker
        volume_level: 0.2
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.kitchen_speaker
        volume_level: 0.3
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.living_room_speaker
        volume_level: 0.3
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.theater_speaker
        volume_level: 0.2
# 8am
- alias: Speakers Volume Set 8am
  trigger:
  - platform: time
    at: "08:00:30"
  action:
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.bathroom_speaker
        volume_level: 0.4
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.bedroom_speaker
        volume_level: 0.5
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.front_patio_speaker
        volume_level: 0.2
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.guest_bathroom_speaker
        volume_level: 0.4
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.guest_room_speaker
        volume_level: 0.5
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.kitchen_speaker
        volume_level: 0.6
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.living_room_speaker
        volume_level: 0.6
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.theater_speaker
        volume_level: 0.5
