
###### INPUT SELECT ------------------------------------------
input_select:

  master_light_scene:
    name: 'Master Light Scene'
    options:
      - bright
      - entertain
      - relax
      - 'off'

###### AUTOMATIONS --------------------------------------
automation:

- alias: Pico Keypad Master Button 1
  trigger:
  - entity_id: sensor.master_bedroom_keypad
    platform: state
    to: "1"
  condition: []
  action:
  - service: script.master_light_scene_bright
- alias: Pico Keypad Master Button 2
  trigger:
  - entity_id: sensor.master_bedroom_keypad
    platform: state
    to: "2"
  condition: []
  action:
  - service: script.master_light_scene_entertain
- alias: Pico Keypad Master Button 3
  trigger:
  - entity_id: sensor.master_bedroom_keypad
    platform: state
    to: "4"
  condition: []
  action:
  - service: script.master_light_scene_relax
- alias: Pico Keypad Master Button 4
  trigger:
  - entity_id: sensor.master_bedroom_keypad
    platform: state
    to: "8"
  condition: []
  action:
  - service: script.master_light_scene_off

- alias: Master Lights Off
  trigger:
  - entity_id: group.lights_master
    platform: state
    to: "off"
  condition: []
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.master_light_scene
      option: 'off'

###### SCRIPT ------------------------------------------
script:

  master_light_scene_bright:
    sequence:
      - service: scene.turn_on
        target:
          entity_id: scene.master_bright
      - service: input_select.select_option
        data:
          entity_id: input_select.master_light_scene
          option: bright
  master_light_scene_entertain:
    sequence:
      - service: scene.turn_on
        target:
          entity_id: scene.master_entertain
      - service: input_select.select_option
        data:
          entity_id: input_select.master_light_scene
          option: entertain
  master_light_scene_relax:
    sequence:
      - service: scene.turn_on
        target:
          entity_id: scene.master_relax
      - service: input_select.select_option
        data:
          entity_id: input_select.master_light_scene
          option: relax
      - service: input_select.select_option
        data:
          entity_id: input_select.master_light_scene
          option: relax
  master_light_scene_off:
    sequence:
      - service: light.turn_off
        target:
          entity_id: group.lights_master
          transistion: 2
      - service: input_select.select_option
        data:
          entity_id: input_select.master_light_scene
          option: 'off'
