
###### INPUT SELECT ------------------------------------------
input_select:

  bed3_light_scene:
    name: 'Bed3 Light Scene'
    options:
      - bright
      - entertain
      - relax
      - 'off'

  bed3_light_scene_relax:
    name: 'Bed3 Light Scene Relax'
    options:
      - reds
      - greens
      - blues
      - yellows
      - whites
      - custom1
      - custom2
      - custom3
      - custom4
      - custom5

###### AUTOMATIONS --------------------------------------
automation:

- alias: Pico Keypad Bed3 Button 1
  trigger:
  - entity_id: sensor.bed3_keypad
    platform: state
    to: "1"
  condition: []
  action:
  - service: script.bed3_light_scene_bright

- alias: Pico Keypad Bed3 Button 2
  trigger:
  - entity_id: sensor.bed3_keypad
    platform: state
    to: "2"
  condition: []
  action:
  - service: script.bed3_light_scene_entertain

- alias: Pico Keypad Bed3 Button 3
  trigger:
  - entity_id: sensor.bed3_keypad
    platform: state
    to: "4"
  condition: []
  action:
  - service: script.bed3_light_scene_relax

- alias: Pico Keypad Bed3 Button 4
  trigger:
  - entity_id: sensor.bed3_keypad
    platform: state
    to: "8"
  condition: []
  action:
  - service: script.bed3_light_scene_off

- alias: Bed3 Lights Off
  trigger:
  - entity_id: group.lights_bed3
    platform: state
    to: "off"
  condition: []
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.bed3_light_scene
      option: 'off'

###### SCRIPT ------------------------------------------
script:

  bed3_light_scene_bright:
    sequence:
      - service: scene.turn_on
        target:
          entity_id: scene.bed3_bright
      - service: input_select.select_option
        data:
          entity_id: input_select.bed3_light_scene
          option: bright
  bed3_light_scene_entertain:
    sequence:
      - service: scene.turn_on
        target:
          entity_id: scene.bed3_entertain
      - service: input_select.select_option
        data:
          entity_id: input_select.bed3_light_scene
          option: entertain
  bed3_light_scene_off:
    sequence:
      - service: scene.turn_on
        target:
          entity_id: scene.bed3_all_off
      - service: input_select.select_option
        data:
          entity_id: input_select.bed3_light_scene
          option: 'off'

# COLORS
  bed3_light_scene_relax:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.bed3_light_scene
          option: relax
      - service: script.turn_on
        target:
          entity_id: script.bed3_light_scene_relax_reds

  bed3_light_scene_relax_reds:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.bed3_light_scene_relax
          option: reds
      - service: scene.turn_on
        target:
          entity_id: scene.bed3_relax_reds

  bed3_light_scene_relax_blues:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.bed3_light_scene_relax
          option: blues
      - service: scene.turn_on
        target:
          entity_id: scene.bed3_relax_blues

  bed3_light_scene_relax_greens:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.bed3_light_scene_relax
          option: greens
      - service: scene.turn_on
        target:
          entity_id: scene.bed3_relax_greens

  bed3_light_scene_relax_yellows:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.bed3_light_scene_relax
          option: yellows
      - service: scene.turn_on
        target:
          entity_id: scene.bed3_relax_yellows

  bed3_light_scene_relax_whites:
    sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.bed3_light_scene_relax
          option: whites
      - service: scene.turn_on
        target:
          entity_id: scene.bed3_relax_whites
