
###### SENSOR TEMPLATES ------------------------------------------
template:
  - sensor:
      - name: "octoprint temp all difference"
        state: >
          {% set tool0 = states('sensor.octoprint_temp_tool0_actual') | float %}
          {% set bed = states('sensor.octoprint_temp_bed_actual') | float %}

          {{ (tool0 - bed) | round(1, default=0) }}
      - name: "octoprint temp bed difference"
        state: >
          {% set bed_actual = states('sensor.octoprint_temp_bed_actual') | float %}
          {% set bed_target = states('sensor.octoprint_temp_bed_target') | float %}

          {{ (bed_target - bed_actual) | round(1, default=0) }}
      - name: "octoprint temp tool0 difference"
        state: >
          {% set tool0_actual = states('sensor.octoprint_temp_tool0_actual') | float %}
          {% set tool0_target = states('sensor.octoprint_temp_tool0_target') | float %}

          {{ (tool0_target - tool0_actual) | round(1, default=0) }}

sensor:
  - platform: template
    sensors:
      octoprint_current_state_rename:
        value_template: >-
          {% if is_state('sensor.octoprint_current_state', 'unavailable') %}
            Disconnected
          {% elif is_state('sensor.octoprint_current_state', 'Printing') %}
            Printing
          {% elif is_state('sensor.octoprint_current_state', 'Operational') %}
            Idle
          {% elif is_state('sensor.octoprint_current_state', 'Starting') %}
            Starting
          {% else %}
            Unknown
          {% endif %}
      octoprint_temp_printer_cooled:
        value_template: "{{ states('sensor.octoprint_temp_all_difference') | float < 20.0 }}"
      octoprint_temp_bed_heating:
        value_template: "{{ states('sensor.octoprint_temp_bed_difference') | float > 3.0 }}"
      octoprint_temp_tool0_heating:
        value_template: "{{ states('sensor.octoprint_temp_tool0_difference') | float > 3.0 }}"

###### AUTOMATIONS --------------------------------------
automation:

- alias: Octoprint Printer Cooled
  trigger:
  - platform: state
    entity_id: sensor.octoprint_temp_printer_cooled
    to: "true"
    for: "00:15:00"
  action:
  - service: switch.turn_off
    data:
      entity_id: switch.octoprint_printer_power
  - service: light.turn_off
    data:
      entity_id: group.lights_living_closet
