
###### SENSOR TEMPLATES ------------------------------------------
template:
  - sensor:
      - name: "Octoprint Temperature Difference"
#        unit_of_measurement: "°C"
        state: >
          {% set tool0 = states('sensor.octoprint_actual_tool0_temp') | float %}
          {% set bed = states('sensor.octoprint_actual_bed_temp') | float %}

          {{ (tool0 - bed) | round(1, default=0) }}

sensor:
  - platform: template
    sensors:
      octoprint_current_state_rename:
        value_template: >-
          {% if is_state('sensor.octoprint_current_state', 'unavailable') %}
            Disconnected
          {% elif is_state('sensor.octoprint_current_state', 'Printing') %}
            Creating
          {% elif is_state('sensor.octoprint_current_state', 'Operational') %}
            Idle
          {% elif is_state('sensor.octoprint_current_state', 'Starting') %}
            Reboot
          {% else %}
            Unknown
          {% endif %}
      octoprint_printer_cooled:
        value_template: "{{ states('sensor.octoprint_actual_tool0_temp') | float < 50.0 }}"

###### AUTOMATIONS --------------------------------------
automation:

- alias: Octoprint Printer Cooled
  trigger:
  - platform: state
    entity_id: sensor.octoprint_printer_cooled
    to: "True"
    for: "00:15:00"
  action:
  - service: switch.turn_off
    data:
      entity_id: switch.octoprint_printer_power
