
###### SENSOR TEMPLATES ------------------------------------------

sensor:
  - platform: template
    sensors:
      octoprint_current_state_rename:
        value_template: >-
          {% if is_state('sensor.octoprint_current_state', 'unavailable') %}
            Disconnected
          {% elif is_state('sensor.octoprint_current_state', 'Printing') %}
            Creating
          {% elif is_state('sensor.octoprint_current_state', 'Operational') %}
            Idle
          {% elif is_state('sensor.octoprint_current_state', 'Starting') %}
            Reboot
          {% else %}
            Unknown
          {% endif %}
      octoprint_printer_power_draw:
        value_template: "{{ state_attr('switch.printer_power', 'current_power_w') }}"
      octoprint_printer_cooled:
        value_template: "{{ states('sensor.octoprint_actual_tool0_temp') | float < 50.0 }}"

###### AUTOMATIONS --------------------------------------
automation:

- alias: Octoprint Printer Cooled
  trigger:
  - platform: state
    entity_id: sensor.octoprint_printer_cooled
    to: "on"
    for: "00:15:00"
  condition:
  - condition: state
    entity_id: sensor.octoprint_current_state
    state: "Idle"
  action:
  - service: switch.turn_off
    data:
      entity_id: switch.printer_power
