
###### SENSOR TEMPLATES ------------------------------------------

sensor:
  - platform: template
    sensors:
      front_gate_status:
        friendly_name: "Front Gate Status"
        value_template: >-
          {% if is_state('switch.relay_front_gate_latch', 'off') %}
            Locked
          {% else %}
            Unlocked
          {% endif %}

      front_door_status:
        friendly_name: "Front Door Status"
        value_template: >-
          {% if is_state('binary_sensor.wyzesense_frontdoor', 'off') and is_state('lock.front_door', 'locked') %}
            Locked
          {% elif is_state('binary_sensor.wyzesense_frontdoor', 'off') and is_state('lock.front_door', 'unlocked') %}
            Closed, Unlocked
          {% elif is_state('binary_sensor.wyzesense_frontdoor', 'on') and is_state('lock.front_door', 'unlocked') %}
            Open
          {% elif is_state('binary_sensor.wyzesense_frontdoor', 'on') and is_state('lock.front_door', 'locked') %}
            Open, Locked
          {% elif is_state('binary_sensor.wyzesense_frontdoor', 'unavailable') and is_state('lock.front_door', 'unlocked') %}
            Unknown, Unlocked
          {% elif is_state('binary_sensor.wyzesense_frontdoor', 'unavailable') and is_state('lock.front_door', 'locked') %}
            Unknown, Locked
          {% else %}
            Unknown
          {% endif %}

      garage_door_contact:
        friendly_name: "Garage Door Contact"
        value_template: >-
          {% if is_state('binary_sensor.wyzesense_garagedoor', 'off') %}
            Open
          {% else %}
            Closed
          {% endif %}

      battery_frontdoor_lock:
        value_template: "{{ state_attr('zwave.schlage_allegion_be469_touchscreen_deadbolt', 'battery_level') }}"
      battery_frontdoor_contact:
        value_template: "{{ state_attr('binary_sensor.wyzesense_frontdoor', 'battery_level') }}"
      battery_garagedoor_contact:
        value_template: "{{ state_attr('binary_sensor.wyzesense_garagedoor', 'battery_level') }}"


###### INPUT BOOLEANS ------------------------------------------

input_boolean:
  notify_garage:
    name: Garage Notifications
    initial: on

###### GROUPS ----------------------------------------

group:
 all_persons:
  name: All Persons
  entities:
  - person.ian
#  - person.kalene
  - person.nathan

###### AUTOMATIONS --------------------------------------
automation:
## Lock Up
# Nobody Home
#- alias: Nobody Home - Lock Up
#  trigger:
#  - platform: state
#    entity_id: group.all_persons
#    to: not_home
#    for: "00:30:00"
#  action:
#  - service: cover.close_cover
#    data:
#      entity_id: cover.garage_door


### Front Door
# Midnight
- alias: Lock Up 12am
  trigger:
  - platform: time
    at: "23:59:55"
  action:
  - service: cover.close_cover
    data:
      entity_id: cover.garage_door
  - service: script.turn_on
    data_template:
      entity_id: >
        {% if is_state('binary_sensor.wyzesense_frontdoor', 'off') %}
          script.front_door_lock
        {% else %}
          script.front_door_cannot_lock
        {% endif %}

# 1am
- alias: Lock Up 1am
  trigger:
  - platform: time
    at: "00:59:55"
  action:
  - service: cover.close_cover
    data:
      entity_id: cover.garage_door
  - service: script.turn_on
    data_template:
      entity_id: >
        {% if is_state('binary_sensor.wyzesense_frontdoor', 'off') %}
          script.front_door_lock
        {% else %}
          script.front_door_cannot_lock
        {% endif %}

# 2am
- alias: Lock Up 2am
  trigger:
  - platform: time
    at: "01:59:55"
  action:
  - service: cover.close_cover
    data:
      entity_id: cover.garage_door
  - service: script.turn_on
    data_template:
      entity_id: >
        {% if is_state('binary_sensor.wyzesense_frontdoor', 'off') %}
          script.front_door_lock
        {% else %}
          script.front_door_cannot_lock
        {% endif %}

# 3am
- alias: Lock Up 3am
  trigger:
  - platform: time
    at: "02:59:55"
  action:
  - service: cover.close_cover
    data:
      entity_id: cover.garage_door
  - service: script.turn_on
    data_template:
      entity_id: >
        {% if is_state('binary_sensor.wyzesense_frontdoor', 'off') %}
          script.front_door_lock
        {% else %}
          script.front_door_cannot_lock
        {% endif %}


###### SCRIPTS ------------------------------------------
script:

# Lock Front Door
  front_door_lock:
    sequence:
      - service: lock.lock
        data:
          entity_id: lock.front_door

# Front Door Open During Lock Command
#  front_door_cannot_lock:
#    sequence:
#      - service: camera.snapshot
#        data:
#          entity_id: camera.frontdoor
#          filename: '/config/www/front_door.jpg'
#      - service: !secret notify_ian
#        data:
#          title: Front Door Open
#          message: Door Cannot Lock
#          data:
#            push:
#              category: front_door_unlocked
#            attachment:
#              url: !secret snapshot_frontdoor
