
cover:
  - platform: template
    covers:
      shades_master:
        device_class: shade
        friendly_name: "Kave Blackout"
        value_template: "{{ states('input_select.kave_shade_blackout') }}"
        open_cover:
          service: script.kave_shade_blackout_open
        close_cover:
          service: script.kave_shade_blackout_close
        stop_cover:
          service: script.kave_shade_blackout_stop

###### SENSOR TEMPLATES ------------------------------------------
#sensor:

###### INPUT BOOLEANS ------------------------------------------
#input_boolean:

###### INPUT SELECT ------------------------------------------
input_select:
  kave_shade_blackout:
    name: 'Kave Blackout'
    options:
      - open
      - opening
      - favorite
      - closing
      - closed


###### AUTOMATIONS --------------------------------------
automation:
- alias: Kave Blackout Open
  trigger:
  - platform: state
    entity_id: input_select.kave_shade_blackout
    to: "opening"
    for: "00:00:11"
  condition:
  - condition: template
    value_template: "{{ trigger.from_state.state != 'closed' }}"
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.kave_shade_blackout
      option: open
- alias: Kave Blackout Closed
  trigger:
  - platform: state
    entity_id: input_select.kave_shade_blackout
    to: "closing"
    for: "00:00:11"
  condition:
  - condition: template
    value_template: "{{ trigger.from_state.state != 'open' }}"
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.kave_shade_blackout
      option: closed
- alias: Kave Blackout Open Full Motion
  trigger:
  - platform: state
    entity_id: input_select.kave_shade_blackout
    to: "opening"
    for: "00:00:19"
  condition: []
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.kave_shade_blackout
      option: open
- alias: Kave Blackout Closed Full Motion
  trigger:
  - platform: state
    entity_id: input_select.kave_shade_blackout
    to: "closing"
    for: "00:00:19"
  condition: []
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.kave_shade_blackout
      option: closed

###### SCRIPTS ------------------------------------------
script:
  kave_shade_blackout_open:
    sequence:
      - service: switch.turn_on
        data:
          entity_id: switch.relay_somfy_open
      - service: switch.turn_off
        data:
          entity_id: switch.relay_somfy_open
      - service: input_select.select_option
        data:
          entity_id: input_select.kave_shade_blackout
          option: opening
  kave_shade_blackout_stop:
    sequence:
      - service: switch.turn_on
        data:
          entity_id: switch.relay_somfy_stop
      - service: switch.turn_off
        data:
          entity_id: switch.relay_somfy_stop
      - service: input_select.select_option
        data:
          entity_id: input_select.kave_shade_blackout
          option: favorite
  kave_shade_blackout_close:
    sequence:
      - service: switch.turn_on
        data:
          entity_id: switch.relay_somfy_close
      - service: switch.turn_off
        data:
          entity_id: switch.relay_somfy_close
      - service: input_select.select_option
        data:
          entity_id: input_select.kave_shade_blackout
          option: closing
