
#cover:
#  - platform: template
#    covers:
#      shade_bed3_screen:
#        device_class: shade
#        friendly_name: "Bed3 Screen"
#        value_template: "{{ states('input_select.bed3_shade_screen') }}"
#        open_cover:
#          service: script.bed3_shade_screen_open
#        close_cover:
#          service: script.bed3_shade_screen_close
#        stop_cover:
#          service: script.bed3_shade_screen_stop

###### SENSOR TEMPLATES ------------------------------------------
#sensor:

###### INPUT BOOLEANS ------------------------------------------
#input_boolean:

###### INPUT SELECT ------------------------------------------
input_select:
  bed3_shade_screen:
    name: 'Bed3 Screen'
    options:
      - open
      - opening
      - favorite
      - closing
      - closed


###### AUTOMATIONS --------------------------------------
automation:
- alias: Bed3 Screen Open
  trigger:
  - platform: state
    entity_id: input_select.bed3_shade_screen
    to: "opening"
    for: "00:00:11"
  condition:
  - condition: template
    value_template: "{{ trigger.from_state.state != 'closed' }}"
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.bed3_shade_screen
      option: open
- alias: Bed3 Screen Closed
  trigger:
  - platform: state
    entity_id: input_select.bed3_shade_screen
    to: "closing"
    for: "00:00:11"
  condition:
  - condition: template
    value_template: "{{ trigger.from_state.state != 'open' }}"
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.bed3_shade_screen
      option: closed
- alias: Bed3 Screen Open Full Motion
  trigger:
  - platform: state
    entity_id: input_select.bed3_shade_screen
    to: "opening"
    for: "00:00:19"
  condition: []
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.bed3_shade_screen
      option: open
- alias: Bed3 Screen Closed Full Motion
  trigger:
  - platform: state
    entity_id: input_select.bed3_shade_screen
    to: "closing"
    for: "00:00:19"
  condition: []
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.bed3_shade_screen
      option: closed

###### SCRIPTS ------------------------------------------
script:
  bed3_shade_screen_open:
    sequence:
      - service: switch.turn_on
        data:
          entity_id: switch.relay_bed3_screen_open
      - service: switch.turn_off
        data:
          entity_id: switch.relay_bed3_screen_open
      - service: input_select.select_option
        data:
          entity_id: input_select.bed3_shade_screen
          option: opening
  bed3_shade_screen_stop:
    sequence:
      - service: switch.turn_on
        data:
          entity_id: switch.relay_bed3_screen_stop
      - service: switch.turn_off
        data:
          entity_id: switch.relay_bed3_screen_stop
      - service: input_select.select_option
        data:
          entity_id: input_select.bed3_shade_screen
          option: favorite
  bed3_shade_screen_close:
    sequence:
      - service: switch.turn_on
        data:
          entity_id: switch.relay_bed3_screen_close
      - service: switch.turn_off
        data:
          entity_id: switch.relay_bed3_screen_close
      - service: input_select.select_option
        data:
          entity_id: input_select.bed3_shade_screen
          option: closing
