
#cover:
#  - platform: template
#    covers:
#      shade_bed3_blackout:
#        device_class: shade
#        friendly_name: "Bed3 Blackout"
#        value_template: "{{ states('input_select.bed3_shade_blackout') }}"
#        open_cover:
#          service: script.bed3_shade_blackout_open
#        close_cover:
#          service: script.bed3_shade_blackout_close
#        stop_cover:
#          service: script.bed3_shade_blackout_stop

###### SENSOR TEMPLATES ------------------------------------------
#sensor:

###### INPUT BOOLEANS ------------------------------------------
#input_boolean:

###### INPUT SELECT ------------------------------------------
input_select:
  bed3_shade_blackout:
    name: 'Bed3 Blackout'
    options:
      - open
      - opening
      - favorite
      - closing
      - closed


###### AUTOMATIONS --------------------------------------
automation:
- alias: Bed3 Blackout Open
  trigger:
  - platform: state
    entity_id: input_select.bed3_shade_blackout
    to: "opening"
    for: "00:00:07"
  condition:
  - condition: template
    value_template: "{{ trigger.from_state.state != 'closed' }}"
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.bed3_shade_blackout
      option: open
- alias: Bed3 Blackout Closed
  trigger:
  - platform: state
    entity_id: input_select.bed3_shade_blackout
    to: "closing"
    for: "00:00:07"
  condition:
  - condition: template
    value_template: "{{ trigger.from_state.state != 'open' }}"
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.bed3_shade_blackout
      option: closed
- alias: Bed3 Blackout Open Full Motion
  trigger:
  - platform: state
    entity_id: input_select.bed3_shade_blackout
    to: "opening"
    for: "00:00:15"
  condition: []
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.bed3_shade_blackout
      option: open
- alias: Bed3 Blackout Closed Full Motion
  trigger:
  - platform: state
    entity_id: input_select.bed3_shade_blackout
    to: "closing"
    for: "00:00:15"
  condition: []
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.bed3_shade_blackout
      option: closed

###### SCRIPTS ------------------------------------------
script:
  bed3_shade_blackout_open:
    sequence:
      - service: cover.open_cover
        data:
          entity_id: cover.bed3_blackout
      - service: input_select.select_option
        data:
          entity_id: input_select.bed3_shade_blackout
          option: opening
  bed3_shade_blackout_stop:
    sequence:
      - service: cover.stop_cover
        data:
          entity_id: cover.bed3_blackout
      - service: input_select.select_option
        data:
          entity_id: input_select.bed3_shade_blackout
          option: favorite
  bed3_shade_blackout_close:
    sequence:
      - service: cover.close_cover
        data:
          entity_id: cover.bed3_blackout
      - service: input_select.select_option
        data:
          entity_id: input_select.bed3_shade_blackout
          option: closing
