
#cover:
#  - platform: template
#    covers:
#      shade_theater_roman:
#        device_class: shade
#        friendly_name: "Theater Roman"
#        value_template: "{{ states('input_select.theater_shade_roman') }}"
#        open_cover:
#          service: script.theater_shade_roman_open
#        close_cover:
#          service: script.theater_shade_roman_close
#        stop_cover:
#          service: script.theater_shade_roman_stop

###### SENSOR TEMPLATES ------------------------------------------
#sensor:

###### INPUT BOOLEANS ------------------------------------------
#input_boolean:

###### INPUT SELECT ------------------------------------------
input_select:
  theater_shade_roman:
    name: 'Theater Roman'
    options:
      - open
      - opening
      - favorite
      - closing
      - closed


###### AUTOMATIONS --------------------------------------
automation:
- alias: Theater Roman Open
  trigger:
  - platform: state
    entity_id: input_select.theater_shade_roman
    to: "opening"
    for: "00:00:07"
  condition:
  - condition: template
    value_template: "{{ trigger.from_state.state != 'closed' }}"
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.theater_shade_roman
      option: open
- alias: Theater Roman Closed
  trigger:
  - platform: state
    entity_id: input_select.theater_shade_roman
    to: "closing"
    for: "00:00:07"
  condition:
  - condition: template
    value_template: "{{ trigger.from_state.state != 'open' }}"
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.theater_shade_roman
      option: closed
- alias: Theater Roman Open Full Motion
  trigger:
  - platform: state
    entity_id: input_select.theater_shade_roman
    to: "opening"
    for: "00:00:15"
  condition: []
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.theater_shade_roman
      option: open
- alias: Theater Roman Closed Full Motion
  trigger:
  - platform: state
    entity_id: input_select.theater_shade_roman
    to: "closing"
    for: "00:00:15"
  condition: []
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.theater_shade_roman
      option: closed

###### SCRIPTS ------------------------------------------
script:
  theater_shade_roman_open:
    sequence:
      - service: cover.open_cover
        data:
          entity_id: cover.theater_roman
      - service: input_select.select_option
        data:
          entity_id: input_select.theater_shade_roman
          option: opening
  theater_shade_roman_stop:
    sequence:
      - service: cover.stop_cover
        data:
          entity_id: cover.theater_roman
      - service: input_select.select_option
        data:
          entity_id: input_select.theater_shade_roman
          option: favorite
  theater_shade_roman_close:
    sequence:
      - service: cover.close_cover
        data:
          entity_id: cover.theater_roman
      - service: input_select.select_option
        data:
          entity_id: input_select.theater_shade_roman
          option: closing
