
###### SENSOR TEMPLATES ------------------------------------------
sensor:
  - platform: template
    sensors:
      now_playing_title_sonos_play5_1:
        friendly_name: Now Playing Sonos Play5 1
        value_template: "{{ state_attr('media_player.sonos_play5_1', 'media_title') }}"

      now_playing_artist_sonos_play5_1:
        friendly_name: Now Playing Sonos Play5 1
        value_template: "{{ state_attr('media_player.sonos_play5_1', 'media_artist') }}"

      now_playing_album_sonos_play5_1:
        friendly_name: Now Playing Sonos Play5 1
        value_template: "{{ state_attr('media_player.sonos_play5_1', 'media_album_name') }}"

###### INPUT BOOLEANS ------------------------------------------
input_boolean:
  sonos_volumes_play5_1:
    name: Sonos 1 Volume
    initial: off

###### GROUPS ----------------------------------------
#group:

###### AUTOMATIONS --------------------------------------
#automation:

###### SCRIPTS ------------------------------------------
#script:
