
###### SENSOR TEMPLATES ------------------------------------------
#sensor:

###### INPUT BOOLEANS ------------------------------------------
input_boolean:
  sprinkler_scheduler:
    name: Sprinkler Scheduling UI
    initial: off

###### INPUT SELECT ------------------------------------------
#input_select:


###### AUTOMATIONS --------------------------------------
automation:
- alias: Sprinklers Auto Off
  trigger:
  - platform: state
    entity_id: switch.sprinklers
    to: "on"
    for: "00:00:30"
  condition: []
  action:
  - service: switch.turn_off
    data:
      entity_id: switch.sprinklers

###### SCRIPTS ------------------------------------------
#script:
