
###### SENSOR TEMPLATES ------------------------------------------
#sensor:

###### INPUT BOOLEANS ------------------------------------------
input_boolean:
  sprinkler_scheduler:
    name: Sprinkler Scheduling UI
    initial: off
  sprinkler_auto_water_1:
    name: Sprinkler Auto Water 1
#    initial: on
  sprinkler_auto_water_2:
    name: Sprinkler Auto Water 2
#    initial: on

###### INPUT SELECT ------------------------------------------
#input_select:


###### AUTOMATIONS --------------------------------------
automation:
- alias: Sprinklers Auto Off
  trigger:
  - platform: state
    entity_id: switch.sprinklers
    to: "on"
    for: "00:00:30"
  condition: []
  action:
  - service: switch.turn_off
    data:
      entity_id: switch.sprinklers

- alias: Sprinklers Schedule 1
  trigger:
  - platform: time
    at: "04:00:00"
  condition:
  - condition: state
    entity_id: input_boolean.sprinkler_auto_water_1
    state: "on"
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.sprinklers
- alias: Sprinklers Schedule 2
  trigger:
  - platform: time
    at: "05:00:00"
  condition:
  - condition: state
    entity_id: input_boolean.sprinkler_auto_water_2
    state: "on"
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.sprinklers

###### SCRIPTS ------------------------------------------
#script:
