###### AUTOMATIONS --------------------------------------
automation:
# Cast Monitored TV Control
- alias: Master TV Cast Started
  trigger:
  - platform: state
    entity_id: media_player.bedroom_tv
    from: "off"
  condition: []
  action:
  - service: media_player.volume_set
    data:
      entity_id: media_player.bedroom_tv
      volume_level: 0.6
  - service: media_player.volume_set
    data:
      entity_id: media_player.bedroom_speaker
      volume_level: 0.3

- alias: Master TV Cast Ended
  trigger:
  - platform: state
    entity_id: media_player.bedroom_tv
    to: "off"
  condition:
  - condition: template
    value_template: "{{ trigger.from_state.state != 'unavailable' }}"
  action:
  - service: script.master_tv_power
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.master_tv_sleep_run
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.master_tv_sleep_show


###### SCRIPTS ------------------------------------------
script:
### Insignia TV
#  Power Toggle
  master_tv_power:
    sequence:
      - service: broadlink.send
        data:
          host: !secret broadlink_master_ip
          packet:
              - "JgBQAAABJ5MTEhM3EzgTEhMSExITEhM3EzgTEhM3ExITEhMSFBITEhM3EzcTNxQ3ExITEhMSExITEhQSExITEhM3EzcTOBM3EwAFowABK0kUAA0FAAAAAAAA"
      - delay:
          milliseconds: 200
#  Picture Mode
  master_tv_picture:
    sequence:
      - service: broadlink.send
        data:
          host: !secret broadlink_master_ip
          packet:
              - "JgBQAAABJpQTEhM3EzcUEhMSExITEhM3EzcTExM3ExITEhMSExITEhM4ExITEhM3ExITEhM3ExMTEhM3EzcTEhM4EzcTEhM3EwAFowABKkoTAA0FAAAAAAAA"
      - delay:
          milliseconds: 200
#  Sleep Timer
  master_tv_sleep:
    sequence:
      - service: broadlink.send
        data:
          host: !secret broadlink_master_ip
          packet:
              - "JgBQAAABJpQTEhM3EzgSExITEhMTEhM3EzgSExI4ExITExISExMSExI4EjgTEhMSEzgSExITEhMSExMSEzcTOBITEjgSOBM3EwAFowABK0oSAA0FAAAAAAAA"
      - delay:
          milliseconds: 200

### Samsung Soundbar
#  Volume Up
  master_soundbar_volume_up:
    sequence:
      - service: broadlink.send
        data:
          host: !secret broadlink_master_ip
          packet:
              - "JgBQAI6SERAREBEQERARMBExERARDxExETASMBExEQ8SDxEQERARkxEPEg8REBEQETARMRExEQ8SMBIvEjAREBEQEQ8REBExERARDxEQETERAA0FAAAAAAAA"
      - delay:
          milliseconds: 200
  master_soundbar_volume_up_3:
    sequence:
      - service: script.master_soundbar_volume_up
      - service: script.master_soundbar_volume_up
      - service: script.master_soundbar_volume_up
#  Volume Down
  master_soundbar_volume_down:
    sequence:
      - service: broadlink.send
        data:
          host: !secret broadlink_master_ip
          packet:
              - "JgCgAI6SEg8REBEQERARMBExERARDxIwETERMBExERARDxEQERARkxEQERARDxEQERAREBEQETARMREwETEREBEwETERMBEQERAREBEQETARAAcUlJIREBEQEQ8REBExETAREBEQETARMRExETAREBEQEQ8SDxGTERAREBEQEQ8REBEQERARMBExETARMREQETARMRExEQ8REBEQERARMBEADQUAAAAAAAA="
      - delay:
          milliseconds: 200
  master_soundbar_volume_down_3:
    sequence:
      - service: script.master_soundbar_volume_down
      - service: script.master_soundbar_volume_down
      - service: script.master_soundbar_volume_down
#  Volume Mute
  master_soundbar_volume_mute:
    sequence:
      - service: broadlink.send
        data:
          host: !secret broadlink_master_ip
          packet:
              - "JgBQAJCSERARDxEQERARMBIwERAREBEwETERMBExERAREBEPERARkxEQERARDxEQETEREBEPERARMREwETEREBEPETERMREwERAREBEQETARAA0FAAAAAAAA"
      - delay:
          milliseconds: 200
#  Woofer Up
  master_soundbar_woofer_up:
    sequence:
      - service: broadlink.send
        data:
          host: !secret broadlink_master_ip
          packet:
              - "JgBQAI+SERAREBAREQ8RMREwERAREBExEDERMREwERAREBEQERAQkxEQERAREBEQERAQMREQERARDxEQERARMREwERARMRAxETERMBExERARAA0FAAAAAAAA"
      - delay:
          milliseconds: 200
#  Woofer Down
  master_soundbar_woofer_down:
    sequence:
      - service: broadlink.send
        data:
          host: !secret broadlink_master_ip
          packet:
              - "JgCgAJCSERAREBEPERARMREwERAREBExETARMREwERAREBEQEQ8RkxEQERAREBEQEDERMREPERAREBEQERARMBEQERARMBExETEQMRExEQ8RAAcUlJIREBEQEBAREBExETAREBEQETARMREwETEREBEQERAQEBGTERAREBEQEBARMRExEBAREBEQERAREBAxERAREBAxETERMBExETEQEBEADQUAAAAAAAA="
      - delay:
          milliseconds: 200
